---
version: '3'
services:
  cc.openssl-generate-certs:
    build:
      context: ../cc-platform/containers/openssl
    command: [ "pwsh", "C:\\config\\generate-certs.ps1" ]
    container_name: openssl
    logging:
      driver: local
    volumes:
      - type: bind
        source: ${PATH_TO_CC_PLATFORM_REPO}/config/openssl
        target: C:/config
        read_only: true
      - type: volume
        source: rabbitmq-local-keys
        target: C:/local-keys
        read_only: false
      - type: volume
        source: rabbitmq-local-certs
        target: C:/local-certs
        read_only: false
      - type: volume
        source: rabbitmq-remote-keys
        target: C:/remote-keys
        read_only: false
      - type: volume
        source: rabbitmq-remote-certs
        target: C:/remote-certs
        read_only: false
volumes:
  rabbitmq-local-keys:
  rabbitmq-remote-keys: # TODO convert to docker secrets
  rabbitmq-local-certs:
  rabbitmq-remote-certs:
