---
version: '3.9'

services:

  cc.drex-service:
    container_name: drex-service
    depends_on:
      - cc.vector-site
      - cc.rabbitmq-local
    environment:
      - SiteConfigFileName=${DREX_SITE_CONFIG_FILE_NAME}
    entrypoint: |
      cmd /Q /C echo Importing rabbitmq certificates into root CA key store... && \
      certoc.exe -addstore root C:\rabbitmq-local-certs\rabbitmq.cer && \
      certoc.exe -addstore root C:\rabbitmq-remote-certs\rabbitmq.cer && \
      echo Imported rabbitmq certificates && \
      echo Starting D-REX... && \
      dotnet Abs.CommonCore.Drex.Console.dll
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_DREX_REPO}/config/drex
        target: C:/app/config
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
