---
version: '3'

services:

  cc.drex-service:
    container_name: drex-service
    depends_on:
      - cc.vector-site
      - cc.rabbitmq-local
    environment:
      - SiteConfigFileName=${DREX_SITE_CONFIG_FILE_NAME}
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_DREX_REPO}/config/drex
        target: C:/app/config
        read_only: true
      - type: volume
        source: rabbitmq-local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: volume
        source: rabbitmq-remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
      - type: bind
        source: ${PATH_TO_CC_PLATFORM_REPO}/config/drex-service
        target: C:/bootstrap
        read_only: true
