---
version: '3'

services:

  cc.vector:
    build:
      context: ${PATH_TO_CC_PLATFORM_REPO}/containers/vector
      dockerfile: Dockerfile
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "infrastructure"
