---
version: '3'

services:

  cc.vector:
    container_name: vector-s
    build:
      context: ${PATH_TO_CC_PLATFORM_REPO}/containers/vector
      dockerfile: Dockerfile
      labels:
        org.eagle.wavesight.container_type: "infrastructure"