---
version: '3.9'

services:

  cc.vector-template:
    # This is never used, but must be here in order to be a valid compose file
    image: ghcr.io/abs-wavesight/vector:windows-${WINDOWS_VERSION}

  cc.vector-site:
    image: ghcr.io/abs-wavesight/vector:windows-${WINDOWS_VERSION}

  cc.vector-central:
    image: ghcr.io/abs-wavesight/vector:windows-${WINDOWS_VERSION}
