---
version: '3'

services:

  cc.vector:
    command: [ "-c", "C:\\config\\vector.toml", "-c", "C:\\config\\vector-loki.toml", "--log-format", "json", "--color", "never" ]
    depends_on: # TODO RH: Make sure this is merged, so that it is depending on rabbit AND loki, not just loki
      cc.loki:
        condition: service_healthy