---
version: '3.9'

services:

  cc.disco-service:
    container_name: disco-service
    depends_on:
      - cc.rabbitmq-local
      - cc.vector-site
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12445:5000"
    restart: always
    volumes:
      - type: volume
        source: disco-scheduler-storage
        target: C:/app/scheduler/data
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      # Copy siemens-adapter config. If we add more adapters in the same way, 
      # it will override the folder with last one.
      - type: bind
        source: ${PATH_TO_CC_SIEMENS_ADAPTER_REPO}/config/vendor-configs
        target: C:/app/config/vendor-configs
        read_only: true

volumes:
  disco-scheduler-storage: