---
version: '3.9'

services:

  cc.disco-service:
    build:
      context: ${PATH_TO_CC_DISCO_REPO}
      dockerfile: service/DISCO.Dockerfile
      args:
        ABS_NUGET_USERNAME: $ABS_NUGET_USERNAME
        ABS_NUGET_PASSWORD: $ABS_NUGET_PASSWORD
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "application"
