auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn # info is the default value. Options include [debug, info, warn, error]
  log_format: json # Options include [logfmt, json]

common:
  path_prefix: C:\Users\containeruser\loki
  storage:
    filesystem:
      chunks_directory: C:\Users\containeruser\loki\chunks
      rules_directory: C:\Users\containeruser\loki\rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper # for more info, see https://grafana.com/docs/loki/latest/storage/#storage
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
