name: Create Azure Key Vault Secret

# on:
#   workflow_call:
inputs:
  keyvault_name:
    description: "Specifies the Azure Key Vault to add a secret to"
    required: true
    type: string
  secret_name:
    description: "Specifies the secret name to add to Azure Key Vault"
    required: true
    type: string
  secret_value:
    description: "Specifies the secret value associated to the name to add to Azure Key Vault"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login via Azure CLI
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TF_APIM_TENANT }}"}'

    - name: Set AZ Subscription
      shell: bash
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set Secret to Key Vault
      shell: bash
      run: az keyvault secret set --vault-name ${{ inputs.keyvault_name }} --name ${{ inputs.secret_name }} --value ${{ inputs.secret_value }}
