---
services:

  cc.drex-central-message-service:
    container_name: drex-central-message-service
    depends_on:
      - cc.rabbitmq-remote
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=guest
      - LocalMessageBus__Password=guest
      - LocalMessageBus__Port=5672
      - LocalMessageBus__HttpPort=15672
      - LocalMessageBus__Protocol=amqp
      - AdaptersFolderPath=C:/app/config/adapters
      - VesselsFolderPath=C:/app/config/vessels
      - HistoryFolderPath=C:/app/config/history
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12346:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_DREX_REPO}/config/drexcentral
        target: C:/app/config
        read_only: false
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
