[sources.rabbitmq]
type = "amqp"
connection_string = "amqps://guest:guest@rabbitmq-central:5671/commoncore"
tls.ca_file = "C:\\certs\\ca.pem"
decoding.codec = "bytes"
consumer = "vector"
queue = "cc.drex.central.snk-log.q"

[transforms.remap-site-logs]
type = "remap"
inputs = ["rabbitmq"]
file = "./config/remap-central-logs.vrl"

[sinks.disk]
type = "file"
inputs = ["remap-site-logs"]
encoding.codec = "json"
compression = "none"
path = "C:\\cc-logs\\{{container_name}}-%Y-%m-%d_%H.log"

[api]
enabled = true
address = "0.0.0.0:8686"
playground = true
