[sources.rabbitmq]
type = "amqp"
connection_string = "amqp://guest:guest@rabbitmq-remote:5673"
decoding.codec = "json"
# compression = "gzip"
consumer = "vector"
# exchange_key = "cc.drex.central.snk-log.ed"
# routing_key_field = "cc.drex.central.snk-log.q"
queue = "cc.drex.central.snk-log.q"

[transforms.remap-site-logs]
type = "remap"
inputs = ["rabbitmq"]
file = "./config/remap-site-logs.vrl"

[sinks.disk]
type = "file"
inputs = ["remap-site-logs"]
encoding.codec = "json"
compression = "none"
path = "C:\\cc-logs\\{{container_name}}-%Y-%m-%d_%H.log"
