services:

  cc.rabbitmq-template: &rabbitmq
    logging:
      driver: local
    profiles: [ 'templates' ]
    restart: always
    entrypoint: [ cmd, "-c" ]
    command:
      [
        "certoc.exe -addstore root c:\\certs\\rabbitmq.cer",
        ";",                
        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-server.bat"
      ]
    healthcheck:
      test:
        [
          "CMD", 
          "curl",
          "-k",
          "--head", 
          "https://localhost:15671"
        ]
      interval: 10s
      timeout: 15s
      # start_period is set high because it takes awhile to start up, especially when starting multiple instances of rabbitmq simultaneously
      start_period: 120s
      retries: 1
    volumes:
      - &config_volume
        type: bind
        source: ${PATH_TO_CC_PLATFORM_REPO}/config/rabbitmq/
        target: C:/rabbitmq/config
        read_only: true

  cc.rabbitmq-local:
    <<: *rabbitmq
    container_name: rabbitmq-vessel
    environment:
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILES: C:\rabbitmq\config
      RABBITMQ_LOCATION: vessel
    hostname: rabbitmq-vessel
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
      - "15671:15671"
    profiles: [ 'rabbitmq-local' ]
    volumes:
      - *config_volume
      - type: volume
        source: rabbitmq-vessel-storage
        target: C:/data
      - type: bind
        source: ${PATH_TO_CERTS}/local-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/certs
        read_only: true
      - type: bind	
        source: ${PATH_TO_CC_PLATFORM_REPO}/logs/site
        target: C:/data

  cc.rabbitmq-remote:
    <<: *rabbitmq
    container_name: rabbitmq-central
    environment:
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILES: C:\rabbitmq\config
      RABBITMQ_LOCATION: central
    hostname: rabbitmq-central
    ports:
      - "5682:5672"
      - "15682:15672"
      - "5681:5671"
      - "15681:15671"
    profiles: [ 'rabbitmq-remote' ]
    volumes:
      - *config_volume
      - type: volume
        source: rabbitmq-central-storage
        target: C:/data
      - type: bind
        source: ${PATH_TO_CERTS}/remote-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/certs
        read_only: true
      - type: bind	
        source: ${PATH_TO_CC_PLATFORM_REPO}/logs/central
        target: C:/data

volumes:
  rabbitmq-vessel-storage:
  rabbitmq-central-storage:
