services:

  cc.rabbitmq-template:
    # This is never used, but must be here in order to be a valid compose file
    image: abs-cc-cc.rabbitmq-local:latest

  cc.rabbitmq-local:
    image: abs-cc-cc.rabbitmq-local:latest

  cc.rabbitmq-remote:
    image: abs-cc-cc.rabbitmq-local:latest
