services:

  cc.rabbitmq-template: &rabbitmq
    logging:
      driver: local
    profiles: [ 'templates' ]
    restart: always
    entrypoint: [ "powershell", "-c" ]
    command:
      [
        "Import-Certificate",
        "-CertStoreLocation",
        "Cert:\\LocalMachine\\root",
        "-FilePath",
        "C:\\certs\\rabbitmq.cer",
        ";",

        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-plugins.bat", 
        "enable", 
        "rabbitmq_shovel", 
        ";",

        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-plugins.bat", 
        "enable", 
        "rabbitmq_shovel_management",
        ";",
                
        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-server.bat"
      ]
    healthcheck:
      test:
        [
          "CMD",
          "powershell",
          "-Command",
          "Invoke-WebRequest",
          "-UseBasicParsing",
          "-Method",
          "HEAD",
          "-Uri",
          "https://localhost:15671"
        ]
      interval: 10s
      timeout: 15s
      # start_period is set high because it takes awhile to start up, especially when starting multiple instances of rabbitmq simultaneously
      start_period: 120s
      retries: 1
    volumes:
      - &config_volume
        type: bind
        source: ${PATH_TO_CC_PLATFORM_REPO}/config/rabbitmqcore/
        target: C:/rabbitmq/config
        read_only: true

  cc.rabbitmq-local:
    <<: *rabbitmq
    container_name: rabbitmq-vessel
    environment:
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILES: C:\rabbitmq\config
      RABBITMQ_LOCATION: vessel
    hostname: rabbitmq-vessel
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
      - "15671:15671"
    profiles: [ 'rabbitmq-local' ]
    volumes:
      - *config_volume
      - type: volume
        source: rabbitmq-vessel-storage
        target: C:/data/rabbitmq
      - type: bind
        source: ${PATH_TO_CERTS}/local-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/certs
        read_only: true

  cc.rabbitmq-remote:
    <<: *rabbitmq
    container_name: rabbitmq-central
    environment:
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILES: C:\rabbitmq\config
      RABBITMQ_LOCATION: central
    hostname: rabbitmq-central
    ports:
      - "5682:5672"
      - "15682:15672"
      - "5681:5671"
      - "15681:15671"
    profiles: [ 'rabbitmq-remote' ]
    volumes:
      - *config_volume
      - type: volume
        source: rabbitmq-central-storage
        target: C:/data/rabbitmq
      - type: bind
        source: ${PATH_TO_CERTS}/remote-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/certs
        read_only: true

volumes:
  rabbitmq-vessel-storage:
  rabbitmq-central-storage:
