---
version: '3.9'

services:

  cc.drex-file-service:
    container_name: drex-file-service
    depends_on:
      - cc.vector-site
      - cc.rabbitmq-local
      - cc.drex-message-service
    environment:
      - SiteConfigFileName=${DREX_SITE_CONFIG_FILE_NAME}
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
    ports:
      - "12346:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_DREX_REPO}/config/drex
        target: C:/app/config
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
