---
services:

  cc.drex-message-service:
    container_name: drex-message-service
    depends_on:
      - cc.rabbitmq-local
    environment:
      - SiteConfigFileName=${DREX_SITE_CONFIG_FILE_NAME}
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - ABS_CC_FDZ_PATH=c:/fdz
      - ABS_CC_SSH_KEYS_PATH=c:/ssh-keys
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_DREX_REPO}/config/drex
        target: C:/app/config
        read_only: false
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
      - type: bind
        source: ${ABS_CC_FDZ_PATH}
        target: c:/fdz
        read_only: false
      - type: bind
        source: ${ABS_CC_SSH_KEYS_PATH}
        target: c:/ssh-keys
        read_only: false 