name: .NET Build + SonarQube Scanner
description: Builds .NET project and runs SonarQube scanner
inputs:
  solution-directory:
    required: true
    description: Relative to the repository root (e.g., "service")
  solution-name:
    required: true
    description: Should be found with the `solution-directory` (e.g., "Drex.sln")
  sonar-project-key:
    required: true
    description: "Reposiroty ID in SonarQube"
  sonar-token:
    required: true
    description: "SonarQube Token"

runs:
  using: "composite"
  steps:
    # 1.------------------ CONFIGURE SONARQUBE ------------------- #
    - name: Set Sonar branch name
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "adopt"

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: .\.sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarQube scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Check SonareQube URL Access
      shell: bash
      run: |
        URL="https://sonarqube.absns.cloud"
        HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Failed to access $URL, status code: $HTTP_STATUS"
          exit 1
        else
          echo "Successfully accessed $URL, status code: $HTTP_STATUS"
        fi

    # 2.-----  BUILD SOLUTION with SONARQUBE ANALYSIS-------- #
    - name: Build Solution w/ SonarQube Analysis
      shell: powershell
      run: |
        # Begin SonarQube Analysis
        .\.sonar\scanner\dotnet-sonarscanner begin `
          /k:${{ inputs.sonar-project-key }} `
          /d:sonar.token=${{ inputs.sonar-token }} `
          /d:sonar.host.url="https://sonarqube.absns.cloud" `
          /d:sonar.branch.name=$BRANCH_NAME `
          /d:sonar.ws.timeout=500 `
          /d:sonar.projectBaseDir=${{ github.workspace }} `
          /d:sonar.scanner.skipJreProvisioning=true

        # Build .NET Project
        dotnet build ${{ inputs.solution-directory }}\${{ inputs.solution-name }} -c Release --no-restore

        # End SonarQube Analysis
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token=${{ inputs.sonar-token }} | Tee-Object -FilePath logs.txt

    - name: Export Sonar Report File
      shell: bash
      run: |
        LINE=$(grep "View details on " logs.txt)
        URL=$(echo $LINE | grep -Eo 'https://[^ >]+'|head -1)
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo "sonar_output_url=$URL"
  # ---------------------------------------------------------- #
