---
services:

  cc.voyage-manager-adapter:
    container_name: voyage-manager-adapter
    depends_on:
      - cc.rabbitmq-remote
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CC_VOYAGE_MANAGER_ADAPTER_REPO}/config/VoyageManagerAdapter.Central
        target: C:/app/config
        read_only: false
      - type: bind
        source: ${PATH_TO_CERTS}/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true