services:

  cc.voyage-manager-adapter:
    build:
      context: ${PATH_TO_CC_VOYAGE_MANAGER_ADAPTER_REPO}
      dockerfile: src\VoyageManagerAdapter.Central.Dockerfile
      args:
        ABS_NUGET_USERNAME: $ABS_NUGET_USERNAME
        ABS_NUGET_PASSWORD: $ABS_NUGET_PASSWORD
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "application"
