---
version: '3.9'

services:

  cc.siemens-adapter:
    container_name: siemens-adapter
    depends_on:
      - cc.disco-service
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - FLAT_LOGS=${FLAT_LOGS:-False}
    restart: always
    volumes:
      - type: bind
        source: ${PATH_TO_CERTS}/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true    

