name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      rabbitmq-tag:
        required: true
        type: string
        description: Tag to use for RabbitMQ release
      vector-site-tag:
        required: true
        type: string
        description: Tag to use for Vector site release
      drex-tag:
        required: true
        type: string
        description: Tag to use for Drex release  

concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Site System Release
    uses: ./.github/workflows/shared/shared-system-release.yml
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      windows-version: ${{ inputs.windows-version }}
      tag-prefix: site-system
      system-config: SiteSystemConfig.json
      component-params: -p `$RABBIT_RELEASE_TAG:${{ inputs.rabbitmq-tag }} -p `$VECTOR_SITE_RELEASE_TAG:${{ inputs.vector-site-tag }} -p `$DREX_RELEASE_TAG:${{ inputs.drex-tag }}
      release-name-prefix: Site System Release
    secrets: inherit