[sources.container-logs]
type = "docker_logs"
# NOTE: Unfortunately, "include_labels" is all or nothing, so we cannot use it here to filter on "container_type"; instead, we must apply a filter condition in remap-container-logs
# docker_host = "tcp://172.16.239.1:2376" # Necessary when running with Hyper-V containers on Windows, where the named pipe does not seem to work
exclude_containers = ["vector"] # This is a prefix match, so "vector" will match "vector-site" and "vector-central"

[transforms.remap-container-logs]
type = "remap"
inputs = ["container-logs"]
file = "./config/remap-container-logs.vrl"

[transforms.filter-container-logs-on-container-type]
type = "filter"
inputs = ["remap-container-logs"]
condition = 'exists(.container_type)'

[transforms.filter-container-logs-on-level]
type = "filter"
inputs = ["filter-container-logs-on-container-type"]
condition = '.level == "warn" || .level == "error" || .level == "critical"'

[sinks.disk]
type = "file"
inputs = ["filter-container-logs-on-container-type"]
encoding.codec = "json"
compression = "none" # compression options: ["none", "gzip", "zstd"].
path = "C:\\cc-logs\\{{container_name}}-%Y-%m-%d_%H.log" # Remember to change file extension if enabling compression (e.g. ".gzip" or ".zst")

[sinks.rabbitmq]
type = "amqp"
inputs = ["filter-container-logs-on-level"]
connection_string = "amqps://rabbitmq-local:5671"
tls.ca_file = "C:\\certs\\rabbitmq.cer"
encoding.codec = "json"
exchange = "cc.drex.site.ed"
routing_key = "cc.drex.site.int-log.q"

[api]
enabled = true
address = "0.0.0.0:8686"
playground = true