---
version: '3.9'
services:
  cc.observability-service:
    container_name: observability-service
    hostname: observability-service
    environment:
      - FLAT_LOGS=${FLAT_LOGS:-False}    
    logging:
      driver: local
    ports:
      - 5259:80
    restart: always
    volumes:
      - \\.\pipe\docker_engine:\\.\pipe\docker_engine