---
services:
  cc.observability-service:
    build:
      context: ${PATH_TO_CC_PLATFORM_REPO}
      dockerfile: /services/ObservabilityService/ObservabilityService.Dockerfile
      args:
        ABS_NUGET_USERNAME: $ABS_NUGET_USERNAME
        ABS_NUGET_PASSWORD: $ABS_NUGET_PASSWORD      
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "infrastructure"
