---
services:
  cc.drex-notification-adapter:
    container_name: drex-notification-adapter
    image: ghcr.io/abs-wavesight/drex-notification-adapter:windows-$WINDOWS_VERSION-$DREX_NOTIFICATION_ADAPTER_VERSION
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/ca.pem
      - ConnectionSettings__Username=${DREX_SHARED_LOCAL_USERNAME}
      - ConnectionSettings__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - ABS_CC_SSH_KEYS_PATH=c:/ssh-keys
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12349:5000"
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/drex
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $ABS_PATH/ssh-keys
        target: c:/ssh-keys
        read_only: false
      - type: bind
        source: $ABS_PATH/cc-logs
        target: c:/app/logs
        read_only: false        
