---	
version: '3'	

services:	
  cc.drex-service:	
    container_name: drex-service	
    image: ghcr.io/abs-wavesight/cc-drex-service:windows-$WINDOWS_VERSION	
    depends_on:	
      - cc.vector	
      - cc.rabbitmq	
    environment:	
      - SiteConfigFileName=C:/app/config/site-config.json
    ports:	
      - "12345:5000"	
    restart: always	
    volumes:	
      - type: bind	
        source: c:/config/drex	
        target: C:/app/config	
        read_only: true