---
services:
  cc.rabbitmq:
    container_name: rabbitmq
    image: ghcr.io/abs-wavesight/rabbitmq:windows-$WINDOWS_VERSION-main-$PLATFORM_COMMIT_SHA
    hostname: rabbitmq-$RABBIT_LOCATION
    entrypoint: [ "powershell", "-c" ]
    command:
      [
        "Import-Certificate",
        "-CertStoreLocation",
        "Cert:\\LocalMachine\\root",
        "-FilePath",
        "C:\\certs\\rabbitmq.cer",
        ";",

        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-plugins.bat", 
        "enable", 
        "rabbitmq_shovel", 
        ";",

        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-plugins.bat", 
        "enable", 
        "rabbitmq_shovel_management",
        ";",
                
        "cmd",
        "/C",
        "c:\\rabbitmq\\sbin\\rabbitmq-server.bat"
      ]
    healthcheck:
      test:
        [
          "CMD",
          "powershell",
          "-Command",
          "Invoke-WebRequest",
          "-UseBasicParsing",
          "-Method",
          "HEAD",
          "-Uri",
          "https://localhost:15671"
        ]
      interval: 10s
      timeout: 15s
      start_period: 120s
      retries: 1
    environment:	
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILE: C:/rabbitmq/config/cc-rabbitmq.conf
      RABBITMQ_LOCATION: $RABBIT_LOCATION
    logging:	
      driver: local    	
    restart: always
    ports:	
      - "5671:5671"	
      - "5672:5672"	
      - "15671:15671"
    volumes:
      - type: volume
        source: rabbitmq-storage
        target: C:/data/rabbitmq
      - type: bind	
        source: $ABS_PATH/config/rabbitmq	
        target: C:/rabbitmq/config
        read_only: true	
      - type: bind
        source: $ABS_PATH/certificates/local-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/certs
        read_only: true

volumes:
  rabbitmq-storage:
