---
services:
  cc.rabbitmq:
    container_name: rabbitmq
    image: ghcr.io/abs-wavesight/rabbitmq:windows-$WINDOWS_VERSION-$RABBITMQ_NANO_VERSION
    hostname: rabbitmq-$RABBIT_LOCATION
    deploy:
      resources:
        limits:
          memory: 8G
    entrypoint: [ cmd, "-c" ]
    command: [ "certoc.exe -addstore root c:\\certs\\ca.pem", ";", "cmd", "/C", "c:\\rabbitmq\\sbin\\rabbitmq-server.bat" ]
    healthcheck:
      test: [ "CMD", "curl", "-k", "--head", "https://localhost:15671" ]
      interval: 10s
      timeout: 15s
      start_period: 120s
      retries: 1
    environment:
      RABBITMQ_MNESIA_BASE: C:/data/rabbitmq
      RABBITMQ_CONFIG_FILES: C:/rabbitmq/config
      RABBITMQ_LOCATION: $RABBIT_LOCATION
    logging:
      driver: local
    restart: always
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
    volumes:
      - type: volume
        source: rabbitmq-storage
        target: C:/data/rabbitmq
      - type: bind
        source: $ABS_PATH/config/rabbitmqnano
        target: C:/rabbitmq/config
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-keys
        target: C:/keys
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/certs
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/cloud-keys
        target: C:/cloud-keys
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/cloud-certs
        target: C:/cloud-certs
        read_only: true

volumes:
  rabbitmq-storage:
