---
version: '3.9'
services:
  cc.sftp-service:
    image: ghcr.io/abs-wavesight/cc-observability-service:windows-$WINDOWS_VERSION-main-$PLATFORM_COMMIT_SHA    
    container_name: observability-service
    hostname: observability-service
    environment:
      - FLAT_LOGS=${FLAT_LOGS:-False}    
    logging:
      driver: local
    ports:
      - 5259:5259
    restart: always	