---
version: '3.9'
services:
  cc.openssl-generate-certs:
    image: ghcr.io/abs-wavesight/openssl:windows-${WINDOWS_VERSION}
    command: [ "pwsh", "C:\\config\\generate-certs-prod.ps1" ]
    container_name: openssl
    logging:
      driver: local
    volumes:
      - type: bind
        source:  $ABS_PATH/config/openssl
        target: C:/config
        read_only: true
      - type: volume
        source: rabbitmq-key
        target: C:/key
        read_only: false
      - type: volume
        source: rabbitmq-cert
        target: C:/cert
        read_only: false
volumes:
  rabbitmq-key:
  rabbitmq-cert:
