---
services:
  cc.siemens:
    container_name: siemens
    image: ghcr.io/abs-wavesight/siemens:windows-$WINDOWS_VERSION-$SIEMENS_VERSION
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - BusConnection__username=${SIEMENS_RABBIT_USERNAME}
      - BusConnection__password=${SIEMENS_RABBIT_PASSWORD}
      - FLAT_LOGS=false
    ports:
      - "12446:5000"
    depends_on:
      - cc.rabbitmq
      - cc.disco
    logging:
      driver: local
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $ABS_PATH/config/vendor-configs
        target: C:/app/config/vendor-configs
        read_only: true
