---
services:
  cc.drex-central-message-service:
    container_name: drex-central-message
    image: ghcr.io/abs-wavesight/cc-drex-central-message-service:windows-$WINDOWS_VERSION-main-$DREX_COMMIT_SHA
    depends_on:
      - cc.rabbitmq
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - CloudParameters__CcTenantId=$CC_TENANT_ID
      - CloudParameters__CcTenantName=$CC_TENANT_NAME
      - CloudParameters__CloudTenantId=$CLOUD_TENANT_ID
      - CloudParameters__ApimServiceUrl=$APIM_SERVICE_URL
      - CloudParameters__CloudClientId=$CLOUD_CLIENT_ID
      - CloudParameters__CloudClientSecret=$CLOUD_CLIENT_SECRET
      - AdaptersFolderPath=C:/app/config/adapters
      - VesselsFolderPath=C:/app/config/vessels
      - HistoryFolderPath=C:/app/config/history
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:	
      - "12346:5000"	
    restart: always	
    volumes:
      - type: bind	
        source: $ABS_PATH/config/drexcentral
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-remote-certs
        read_only: true