---
services:
  cc.message-scheduler:
    container_name: message-scheduler
    image: ghcr.io/abs-wavesight/message-scheduler:windows-$WINDOWS_VERSION-$MESSAGE_SCHEDULER_VERSION
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-certs/rabbitmq.cer
      - FLAT_LOGS=${FLAT_LOGS:-False}
      - ConnectionSettings__Username=${MESSAGE_SCHEDULER_USERNAME}
      - ConnectionSettings__Password=${MESSAGE_SCHEDULER_PASSWORD}
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/message-scheduler
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-certs
        read_only: true
