---
services:
  cc.drex-central-service:
    container_name: drex-central-service
    image: ghcr.io/abs-wavesight/cc-drex-central-service:windows-$WINDOWS_VERSION-main-$DREX_COMMIT_SHA
    depends_on:
      - cc.rabbitmq
    environment:
      - SiteConfigFileName=C:/app/config/site-config.json
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - LocalMessageBus__Port=${DREX_SHARED_LOCAL_PORT}
      - LocalMessageBus__HttpPort=${DREX_SHARED_LOCAL_HTTP_PORT}
      - TenantId=${CC_TENANT_ID}
      - TenantName=${CC_TENANT_NAME}
      - ABS_CC_FDZ_PATH=c:/fdz
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:	
      - "12345:5000"	
    restart: always	
    volumes:	
      - type: bind	
        source: $ABS_PATH/config/drex-shared
        target: C:/app/config	
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
      - type: bind
        source: $FDZ_ROOT_PATH
        target: c:/fdz
        read_only: false
      - type: bind
        source: $ABS_PATH/ssh-keys
        target: c:/ssh-keys
        read_only: false 