---
services:
  cc.voyage-manager-report-adapter:
    container_name: voyage-manager-report-adapter
    image: ghcr.io/abs-wavesight/cc-voyage-manager-adapter:windows-$WINDOWS_VERSION-main-$VOYAGE_MANAGER_REPORT_ADAPTER_COMMIT_SHA
    depends_on:
      - cc.rabbitmq
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:	
      - "12345:5000"	
    restart: always	
    volumes:	
      - type: bind	
        source: $ABS_PATH/config/voyage-manager-report-adapter
        target: C:/app/config	
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true