---
services:
  cc.drex-message-service:
    container_name: drex-central-message
    image: ghcr.io/abs-wavesight/drex-central-message:windows-$WINDOWS_VERSION-$DREX_CENTRAL_VERSION
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - CloudParameters__CcTenantId=$CC_TENANT_ID
      - CloudParameters__CcTenantName=$CC_TENANT_NAME
      - CloudParameters__CloudTenantId=$CLOUD_TENANT_ID
      - CloudParameters__ApimServiceUrl=$APIM_SERVICE_URL/vmprovisionadapters/CentralRegistry
      - CloudParameters__CloudClientId=$CLOUD_CLIENT_ID
      - CloudParameters__CloudClientSecret=$CLOUD_CLIENT_SECRET
      - AdaptersFolderPath=C:/app/adapters
      - VesselsFolderPath=C:/app/config/vessels
      - HistoryFolderPath=C:/app/config/history
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/drex-central
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/config/drex-shared/adapters
        target: C:/app/adapters
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
