---
services:

  cc.disco:
    container_name: disco
    image: ghcr.io/abs-wavesight/disco:windows-$WINDOWS_VERSION-$DISCO_VERSION
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/ca.pem
      - ServiceBusConfiguration__BusConnection__username=${DISCO_RABBIT_USERNAME}
      - ServiceBusConfiguration__BusConnection__password=${DISCO_RABBIT_PASSWORD}
      - FLAT_LOGS=false
    ports:
      - "12445:5000"
    depends_on:
      - cc.rabbitmq
    logging:
      driver: local
    restart: always
    volumes:
      - type: volume
        source: disco-scheduler-storage
        target: C:/app/scheduler/data
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $ABS_PATH/config/vendor-configs
        target: C:/app/config/vendor-configs
        read_only: true
      - type: bind
        source: $ABS_PATH/config/client-configs
        target: C:/app/config/client-configs
        read_only: true

volumes:
  disco-scheduler-storage:
