---
services:
  cc.drex-file-service:
    container_name: drex-file-service
    image: ghcr.io/abs-wavesight/cc-drex-file-service:windows-$WINDOWS_VERSION-main-$DREX_COMMIT_SHA
    depends_on:
      - cc.rabbitmq
      - cc.drex-message-service
    environment:
      - SiteConfigFileName=C:/app/config/site-config.json
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - SftpSettings__username=$SFTP_CENTRAL_USERNAME
      - SftpSettings__password=$SFTP_CENTRAL_PASSWORD
      - ABS_CC_FDZ_PATH=c:/fdz
      - ABS_CC_SSH_KEYS_PATH=c:/ssh-keys
      - AdaptersFolderPath=C:/app/adapters
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12346:5002"
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/drex-f
        target: C:/app/config
        read_only: true
      - type: bind
        source: $ABS_PATH/config/drex-shared/adapters
        target: C:/app/adapters
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/central-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
      - type: bind
        source: $FDZ_ROOT_PATH
        target: c:/fdz
        read_only: false
      - type: bind
        source: $ABS_PATH/ssh-keys
        target: c:/ssh-keys
        read_only: false
