---
services:
  cc.file-transfer-scheduler:
    container_name: file-transfer-scheduler
    image: ghcr.io/abs-wavesight/file-transfer-scheduler:windows-$WINDOWS_VERSION-$FILE_TRANSFER_SCHEDULER_VERSION
    environment:
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-certs/ca.pem
      - FLAT_LOGS=${FLAT_LOGS:-False}
      - ConnectionSettings__Username=${MESSAGE_SCHEDULER_USERNAME}
      - ConnectionSettings__Password=${MESSAGE_SCHEDULER_PASSWORD}
      - SchedulerSettings__AdaptersFolderPath=C:/app/config/adapters
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/file-transfer-scheduler
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-certs
        read_only: true
