---
version: '3.9'

services:
  cc.drex-service:
    container_name: drex-service
    image: ghcr.io/abs-wavesight/cc-drex-service:windows-$WINDOWS_VERSION
    depends_on:
      - cc.vector
      - cc.rabbitmq
    environment:
      - SiteConfigFileName=C:/app/config/site-config.json
    entrypoint:
      [
        "cmd",
        "/Q",
        "/C",
        "call",
        "C:\\app\\config\\bootstrap.bat"
      ]
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/drex
        target: C:/app/config
        read_only: true
      - type: volume
        source: rabbitmq-certs
        target: C:/certs
        read_only: true
