---
services:
  cc.drex-message-service:
    container_name: drex-message-service
    image: ghcr.io/abs-wavesight/cc-drex-message-service:windows-$WINDOWS_VERSION-main-$DREX_COMMIT_SHA
    depends_on:
      - cc.rabbitmq
    environment:
      - SiteConfigFileName=C:/app/config/site-config.json
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/rabbitmq.cer
      - RABBITMQ_REMOTE_CERT_PATH=C:/rabbitmq-remote-certs/rabbitmq.cer
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - CentralMessageBus__Username=$DREX_SHARED_CENTRAL_USERNAME
      - CentralMessageBus__Password=$DREX_SHARED_CENTRAL_PASSWORD
      - AdaptersFolderPath=C:/app/config/adapters
      - HistoryFolderPath=C:/app/config/history
      - ABS_CC_FDZ_PATH=c:/fdz
      - ABS_CC_SSH_KEYS_PATH=c:/ssh-keys
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:	
      - "12345:5000"	
    restart: always	
    volumes:	
      - type: bind	
        source: $ABS_PATH/config/drex
        target: C:/app/config	
        read_only: false
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/remote-certs
        target: C:/rabbitmq-remote-certs
        read_only: true
      - type: bind
        source: $FDZ_ROOT_PATH
        target: c:/fdz
        read_only: false
      - type: bind
        source: $ABS_PATH/ssh-keys
        target: c:/ssh-keys
        read_only: false 