---
services:
  cc.drex-message-service:
    container_name: drex-message
    image: ghcr.io/abs-wavesight/drex-message:windows-$WINDOWS_VERSION-$DREX_VESSEL_VERSION
    environment:
      - RABBITMQ_LOCAL_CERT_PATH=C:/rabbitmq-local-certs/ca.pem
      - LocalMessageBus__Username=${DREX_SHARED_LOCAL_USERNAME}
      - LocalMessageBus__Password=${DREX_SHARED_LOCAL_PASSWORD}
      - AdaptersFolderPath=C:/app/adapters
      - HistoryFolderPath=C:/app/config/history
      - ABS_CC_FDZ_PATH=c:/fdz
      - ABS_CC_SSH_KEYS_PATH=c:/ssh-keys
      - FLAT_LOGS=${FLAT_LOGS:-False}
    ports:
      - "12345:5000"
    restart: always
    volumes:
      - type: bind
        source: $ABS_PATH/config/drex
        target: C:/app/config
        read_only: false
      - type: bind
        source: $ABS_PATH/config/drex-shared/adapters
        target: C:/app/adapters
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/rabbitmq-local-certs
        read_only: true
      - type: bind
        source: $FDZ_ROOT_PATH
        target: c:/fdz
        read_only: false
      - type: bind
        source: $ABS_PATH/ssh-keys
        target: c:/ssh-keys
        read_only: false
