---
version: '3.9'
services:
  cc.openssl-generate-certs:
    command: [ "pwsh", "C:\\config\\generate-certs-prod.ps1" ]
    container_name: openssl
    logging:
      driver: local
    volumes:
      - type: bind
        source: $ABS_PATH/config/openssl
        target: C:/config
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-keys
        target: C:/local-keys
        read_only: true
      - type: bind
        source: $ABS_PATH/certificates/local-certs
        target: C:/local-certs
        read_only: true