services:

  cc.system-monitor-adapter:
    build:
      context: ${PATH_TO_CC_SYSTEM_MONITOR_ADAPTER_REPO}
      dockerfile: src\SystemMonitor\Dockerfile
      args:
        ABS_NUGET_USERNAME: $ABS_NUGET_USERNAME
        ABS_NUGET_PASSWORD: $ABS_NUGET_PASSWORD
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "application"