services:

  cc.message-scheduler:
    build:
      context: ${PATH_TO_CC_SCHEDULER_REPO}
      dockerfile: src\MessageScheduler\MessageScheduler.Dockerfile
      args:
        ABS_NUGET_USERNAME: $ABS_NUGET_USERNAME
        ABS_NUGET_PASSWORD: $ABS_NUGET_PASSWORD
      labels:
        org.eagle.wavesight.built_from: "source"
        org.eagle.wavesight.container_type: "application"
