name: Dump Context
description: Dumps context for debugging purposes

runs:
  using: "composite"

  steps:
    - name: Dump context
      shell: pwsh
      env:
        DUMP: ${{ toJSON(github) }}
      run: Write-Output $Env:DUMP