name: Build Installer Media

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

concurrency:
  group: build-installer-media
  cancel-in-progress: true

jobs:
  load-cc-components:
    name: Parse CC Component Registry
    runs-on: windows-latest
    outputs:
      registry: ${{ steps.loadRegistry.outputs.registryContents }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: loadRegistry
        name: "Load Component Registry"
        run: |
          $REGISTRY_CONTENTS = $(GET-Content component_registry.json)
          Write-Output "Registry contents: $REGISTRY_CONTENTS"
          Write-Output "::set-output name=registryContents::$REGISTRY_CONTENTS"
  build-components:
    runs-on: windows-latest  # TODO run on 2019 and 2022?
    needs: load-cc-components
    strategy:
      matrix:
        component: ${{ fromJSON(needs.load-cc-components.outputs.registry).components }}
    steps:
      - name: "Pull Latest Release for ${{ matrix.component.name }}"
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.component.repository_path }}
          token: ${{ secrets.FETCH_RELEASES_TOKEN }}
          ref: "main" # TODO update to pull latest release
          path: ${{ matrix.component.name }}
      - name: "Check file contents"
        run: |
          Get-Content $env:GITHUB_WORKSPACE\${{ matrix.component.name }}\README.md
