name: Create Azure Key Vault Secret

on:
  workflow_call:
    inputs:
      subscription_id:
        description: "Specifies the suncsription id to use for Azure Key Vault"
        required: true
        type: string
      keyvault_name:
        description: "Specifies the Azure Key Vault to add a secret to"
        required: true
        type: string
      secret_name:
        description: "Specifies the secret name to add to Azure Key Vault"
        required: true
        type: string
      secret_value:
        description: "Specifies the secret value associated to the name to add to Azure Key Vault"
        required: true
        type: string

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

runs:
  using: "composite"
  steps:
    - name: Log in to Azure using Service Principal
      shell: bash
      run: az login --service-principal -u ${{ env.ARM_CLIENT_ID }} -p ${{ env.ARM_CLIENT_SECRET }} --tenant ${{ env.ARM_TENANT_ID }}

    - name: Set AZ Subscription
      shell: bash
      run: az account set --subscription ${{ inputs.subscription_id }}

    - name: Set Secret to Key Vault
      shell: bash
      run: az keyvault secret set --vault-name ${{ inputs.keyvault_name }} --name ${{ inputs.secret_name }} --value ${{ inputs.secret_value }}
