name: Deploy Azure Function Apps

on:
  workflow_call:
    inputs:  
      tagVersion:
        description: 'Specifies the Azure Resource Group'
        required: true
        type: string    
      resource_group_name:
        description: 'Specifies the Azure Resource Group'
        required: true
        type: string   
      artifactFunctions:
        description: 'Specifies the name of the artifact containing builded functions'
        required: true
        type: string
      functionAppSuffix:
        description: 'Specifies the function app suffix. Example: dev or qa '
        required: true
        type: string
      artifactConfigName:
        required: true
        type: string
        description: 'Specifies the name of the artifact containing configuration'
      artifactConfigFile:
        required: true
        type: string
        description: 'Specifies the file name in the artifact containing configuration'
    secrets:
      AZURE_CLIENT_ID:
          required: true
      AZURE_AD_CLIENT_SECRET:
          required: true
      AZURE_TENANT_ID:
          required: true
      AZURE_SUBSCRIPTION_ID_DEV:
          required: true
      AZURE_SUBSCRIPTION_ID_QA:
          required: true

jobs: 
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Download config from local Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactConfigName }}
          path: ${{ github.workspace }}/downloaded-artifacts-conf 
      
      - name: List files in target folder
        run: ls -l ${{ github.workspace }}/downloaded-artifacts-conf  

      - name: Download functions from Release Artifacts (Specific Tag)
        uses: robinraju/release-downloader@v1.9
        if: inputs.tagVersion != 'latest'
        with:
          fileName: ${{ inputs.artifactFunctions }}.zip
          tag: ${{ inputs.tagVersion }}
          out-file-path: ${{ github.workspace }}/downloaded-artifacts-func
      
      - name: Download functions from Release Artifacts (Latest)
        uses: robinraju/release-downloader@v1.9
        if: inputs.tagVersion == 'latest'
        with:
          fileName: ${{ inputs.artifactFunctions }}.zip
          latest: true
          out-file-path: ${{ github.workspace }}/downloaded-artifacts-func          

      - name: Manual expand archive files
        shell: pwsh
        run: |
            $destinationPath = "${{ github.workspace }}/downloaded-artifacts-func/functions"
            $zipFilePath = "${{ github.workspace }}/downloaded-artifacts-func/${{ inputs.artifactFunctions }}.zip"
        
            Expand-Archive -Path $zipFilePath -DestinationPath $destinationPath               

      - name: Define Subscription
        id: azure-subscription
        run: |
          if [ ${{ inputs.functionAppSuffix }} = "dev" ]; then
            echo "id=${{ secrets.AZURE_SUBSCRIPTION_ID_DEV  }}" >> $GITHUB_OUTPUT
            echo "Using DEV subscription"
          elif [ ${{ inputs.functionAppSuffix }} = "qa" ]; then
            echo "id=${{ secrets.AZURE_SUBSCRIPTION_ID_QA  }}" >> $GITHUB_OUTPUT
            echo "Using QA subscription"
          else
            echo "::warning::The functionAppSuffix input is not recognized. Expected 'dev' or 'qa', but got ${{ inputs.functionAppSuffix }}."
            exit 1
          fi

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ steps.azure-subscription.outputs.id }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'      

      - name: Azure Function App Zip Deploy
        shell: bash
        run: |         
          artifactPath="${{ github.workspace }}/downloaded-artifacts-conf/${{ inputs.artifactConfigFile }}"
          functionConfigs=$(jq -c '.[]' <"$artifactPath")

          for config in $functionConfigs; do
            use=$(echo $config | jq -r '.Use')
            if [ "$use" = "true" ]; then
              if [ ${{ inputs.functionAppSuffix }} = "dev" ]; then
                functionName=$(echo "$config" | jq -r '.AZURE_FUNCTIONAPP_NAME_DEV')                
              elif [ ${{ inputs.functionAppSuffix }} = "qa" ]; then
                functionName=$(echo "$config" | jq -r '.AZURE_FUNCTIONAPP_NAME_QA')                
              else
                echo "Invalid functionAppSuffix value: ${{ inputs.functionAppSuffix }}"
                exit 1
              fi            
              artifactName=$(echo $config | jq -r '.Name')
              zipFilePath="${{ github.workspace }}/downloaded-artifacts-func/functions/${artifactName}.zip"
              echo "Deploy ${artifactName}"
              echo "Run ${{ inputs.resource_group_name }} ${functionName}  ${zipFilePath}"
              az functionapp deployment source config-zip -g ${{ inputs.resource_group_name }} -n $functionName --src $zipFilePath
            fi
          done  