name: Installer CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/Installer/**/*'
      - '.github/workflows/cc-installer-ci.yml'
      - 'nuget.config'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/Installer/**/*'
      - '.github/workflows/cc-installer-ci.yml'
      - 'nuget.config'
  workflow_dispatch:

concurrency:
  group: cc-installer-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  dump-context:
    name: Dump Context
    uses: ./.github/workflows/shared-dump-context.yml

  build:
    name: Build & Run Tests
    uses: ./.github/workflows/shared-dotnet-build.yml
    with:
      solution-directory: tools/Installer
      solution-name: Installer.sln
      install-docker-compose: false
      check-code-formatting: true
    secrets: inherit