name: Loki CI

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/shared-docker-build-and-push.yml
      - 'containers/loki/**'
      - 'config/loki/**'
      - '.github/workflows/cc-loki-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/shared-docker-build-and-push.yml
      - 'containers/loki/**'
      - 'config/loki/**'  
      - '.github/workflows/cc-loki-ci.yml'

env:
  REGISTRY: ghcr.io
  LABEL_PREFIX: org.eagle.wavesight

concurrency:
  group: cc-loki-ci
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next Version
    uses: ./.github/workflows/shared-define-version.yml
    with:
      major: 1
      minor: 0
      project_marker: "loki"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: true
  
  build-containers:
    needs: [ get-next-version ]
    name: Build Container
    uses: ./.github/workflows/shared-docker-build-and-push.yml
    with:
      image-name: loki
      label-description: ABS Common Core Loki
      docker-context-directory: containers/loki
      solution-directory: containers/loki
      dockerfile-name: Dockerfile
      container-version: ${{ needs.get-next-version.outputs.version }}
      use-submodules: false
      dotnet-version: '8.0.x'  
      container-type: infrastructure
  