name: Local Dev Utility CI Test 3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/LocalDevUtility/**/*'
      - '.github/workflows/cc-local-dev-utility-ci.yml'
      - 'nuget.config'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/LocalDevUtility/**/*'
      - '.github/workflows/cc-local-dev-utility-ci.yml'
      - 'nuget.config'
  workflow_dispatch:

concurrency:
  group: cc-local-dev-utility-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build & Run Tests
    uses: ./.github/workflows/shared-dotnet-build.yml
    with:
      solution-directory: tools/LocalDevUtility
      solution-name: LocalDevUtility.sln
      install-docker-compose: true
      check-code-formatting: true
      run-integration-tests: true
    secrets: inherit

  publish-nuget-package:
    name: Publish Nuget Package
    needs: [build]
    uses: ./.github/workflows/shared-publish-nuget-package.yml
    with:
      solution-directory: tools/LocalDevUtility
      nuget-working-directory: tools/LocalDevUtility/LocalDevUtility
      nuget-package-name: Abs.CommonCore.LocalDevUtility
      project-file: LocalDevUtility/LocalDevUtility.csproj
    secrets: inherit