name: Observability Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/ObservabilityService/**/*'
      - '.github/workflows/cc-observability-service-ci.yml'
      - 'compose/installer/docker-compose.observability-service.yml'
      - 'compose/local-dev/observability-service/*'
      - 'nuget.config'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/ObservabilityService/**/*'
      - '.github/workflows/cc-observability-service-ci.yml'
      - 'compose/installer/docker-compose.observability-service.yml'
      - 'compose/local-dev/observability-service/*'      
      - 'nuget.config'
  workflow_dispatch:

concurrency:
  group: cc-observability-service-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  get-next-version:
    uses: abs-wavesight/cc-platform/.github/workflows/shared-define-version.yml@main
    with:
      major: 1
      minor: 0
      project_marker: "observability"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: true
  
  build-test-publish:
    name: Build, Test, Publish
    uses: abs-wavesight/cc-platform/.github/workflows/shared-dotnet-ci.yml@main
    with:
      image-name: cc-observability-service
      label-description: ABS Common Core Observability Service
      docker-context-directory: .
      solution-directory: services/ObservabilityService
      solution-name: ObservabilityService.sln
      dockerfile-name: ObservabilityService.Dockerfile
      container-version: ${{ needs.get-next-version.outputs.version }}
      check-code-formatting: true
      dotnet-version: '8.0.x'
    secrets: inherit