name: Common Core Platform Package CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'libraries/Platform/**/*'
      - '.github/workflows/cc-platform-package-ci.yml'
      - '.github/workflows/shared-dotnet-build.yml'
      - '.github/workflows/shared-publish-nuget-package.yml'
      - 'nuget.config'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'libraries/Platform/**/*'
      - '.github/workflows/cc-platform-package-ci.yml'
      - '.github/workflows/shared-dotnet-build.yml'
      - '.github/workflows/shared-publish-nuget-package.yml'
      - 'nuget.config'
  workflow_dispatch:

concurrency:
  group: cc-platform-package-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build & Run Tests
    uses: ./.github/workflows/shared-dotnet-build.yml
    with:
      solution-directory: libraries/Platform
      solution-name: CommonCore.Platform.sln
      sonar-project-key: "abs-wavesight_cc-platform_a2f6cd66-bfcc-4a77-a714-29ac0c5d7bef" #Repository ID in SonarQube
      sonar-exclusion-paths: "**/bin/**,**/obj/**,**/TestResults/**,**/Zip Deploy/**,**/*.g.cs,**/*.designer.cs,**/*.Generated.cs,**/*.AssemblyAttributes.cs,**/*.arm.json,submodules/**"                                                            #Comma separated list of paths to exclude from SonarQube analysis
      run-sonar-scan: true                                                                #Toggle to enable or disable SonarQube Scan
      check-code-formatting: true
      run-integration-tests: true
      run-coverage: false
      dotnet-version: '8.0.x'
    secrets: inherit

  publish-nuget-package:
    name: Publish Nuget Package
    needs: [build]
    uses: ./.github/workflows/shared-publish-nuget-package.yml
    with:
      solution-directory: libraries/Platform
      nuget-working-directory: libraries/Platform/CommonCore.Platform
      nuget-package-name: Abs.CommonCore.Platform
      project-file: CommonCore.Platform/CommonCore.Platform.csproj
      dotnet-version: '8.0.x'
    secrets: inherit
