name: RabbitMQ server Core CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/shared-docker-build-and-push.yml'
      - 'containers/rabbitmqcore/**'
      - 'config/rabbitmq/**'
      - 'compose/installer/docker-compose.rabbitmq.yml'
      - '.github/workflows/cc-rabbitmq-core-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/shared-docker-build-and-push.yml'
      - 'containers/rabbitmqcore/**'
      - 'config/rabbitmq/**'
      - 'compose/installer/docker-compose.rabbitmq.yml'
      - '.github/workflows/cc-rabbitmq-core-ci.yml'

env:
  REGISTRY: ghcr.io
  LABEL_PREFIX: org.eagle.wavesight

concurrency:
  group: cc-rabbitmq-core-ci
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next Version
    uses: ./.github/workflows/shared-define-version.yml
    with:
      major: 1
      minor: 0
      project_marker: "rabbitmqcore"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: true
  
  build-containers:
    needs: [ get-next-version ]
    name: Build Container
    uses: ./.github/workflows/shared-docker-build-and-push.yml
    with:
      image-name: rabbitmqcore
      label-description: ABS Common Core RabbitMQ based on Windows Server Core Image
      docker-context-directory: containers/rabbitmqcore
      solution-directory: containers/rabbitmqcore
      dockerfile-name: Dockerfile
      container-version: ${{ needs.get-next-version.outputs.version }}
      use-submodules: false
      dotnet-version: '8.0.x'  
      container-type: infrastructure