name: Sftp Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/SftpService/**/*'
      - '.github/workflows/cc-sftp-service-ci.yml'
      - 'compose/installer/docker-compose.sftp-service.yml'
      - 'compose/local-dev/sftp-service/*'      
      - 'nuget.config'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/SftpService/**/*'
      - '.github/workflows/cc-sftp-service-ci.yml'
      - 'compose/installer/docker-compose.sftp-service.yml'
      - 'compose/local-dev/sftp-service/*'            
      - 'nuget.config'
  workflow_dispatch:

concurrency:
  group: cc-sftp-service-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  get-next-version:
    uses: abs-wavesight/cc-platform/.github/workflows/shared-define-version.yml@main
    with:
      major: 1
      minor: 0
      project_marker: "sftp"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: true
  
  display-version:
    needs: get-next-version
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: echo "Version is ${{ needs.get-next-version.outputs.version }}"

  build-test-publish:
    needs: get-next-version
    name: Build, Test, Publish
    uses: abs-wavesight/cc-platform/.github/workflows/shared-dotnet-ci.yml@main
    with:
      image-name: cc-sftp-service
      label-description: ABS Common Core Sftp Service
      docker-context-directory: .
      solution-directory: services/SftpService
      solution-name: SftpService.sln
      dockerfile-name: SftpService.Dockerfile
      container-version: ${{ needs.get-next-version.outputs.version }}
      check-code-formatting: true
      dotnet-version: 8.0.x
    secrets: inherit