name: Dependency Containers PR Cleanup

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name (MUST replace slashes with dashes)'
        required: true
        type: string

concurrency:
  group: dependency-containers-pr-cleanup-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  clean-container-images:
    name: Clean Container Images
    uses: ./.github/workflows/shared/shared-cleanup-after-pr-merge.yml
    with:
      image-names: "['rabbitmq', 'vector', 'loki', 'grafana']"