name: External Release

on:
  workflow_dispatch:
    inputs:
      internal_release_tag:
        description: 'Internal Release Tag'
        required: true
        type: string
      external_release_name:
        description: 'External Release Name'
        required: true
        type: string
      external_tag:
        description: 'External Tag'
        required: true
        type: string
      release_description:
        description: 'Release Description'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ vars.RELEASE_REPOSITORY }}
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

  publish-release:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      release_url: ${{ steps.publish-release.outputs.html_url }}
      release_name: ${{ steps.get-release-name.outputs.name }}
    env: 
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Copy Release Files
      run: |
        gh release download ${{ github.event.inputs.internal_release_tag }} --dir ./${{ github.event.inputs.internal_release_tag }}
        
    - name: Get Release Name
      id: get-release-name
      run: |
        release_name=$(gh release view ${{ github.event.inputs.internal_release_tag }} --json "name" -q ".name")
        actual_name=$(echo "$release_name" | sed -E 's/^v[0-9]+ //')
        echo "name=$actual_name" >> $GITHUB_OUTPUT

    - name: Publish release
      id: publish-release
      uses: ncipollo/release-action@v1
      with:
        body: ${{ inputs.release_description }}
        name: ${{ inputs.external_release_name }}
        tag: ${{ inputs.external_tag }}
        repo: ${{ vars.RELEASE_REPOSITORY }}
        artifacts: "./${{ github.event.inputs.internal_release_tag }}/*"
        token: ${{ secrets.GH_PAT }}

  push-release:
    needs: [publish-release]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ vars.RELEASE_REPOSITORY }}
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Release changes
      run: |
        base_dir="${{ needs.publish-release.outputs.release_name }}/${{ github.event.inputs.external_tag }} (${{ github.event.inputs.internal_release_tag }})"
        mkdir -p "$base_dir/Installer" "$base_dir/Docs" "$base_dir/Configs"

        echo "# Release Information" > "$base_dir/Installer/Readme.md"
        echo "Release URL: ${{ needs.publish-release.outputs.release_url }}" >> "$base_dir/Installer/Readme.md"

    - name: Commit & Push changes
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ secrets.GH_PAT }}
        message: "Release ${{ github.event.inputs.external_release_name }} - ${{ github.event.inputs.external_tag }}"
        repository: ${{ vars.RELEASE_REPOSITORY }}