name: RabbitMq Release

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: Name of the release
      tag:
        required: true
        type: string
        description: Unique tag for the release
      version-number:
        required: true
        type: string
        description: Unique version number for the release
      readme:
        required: true
        type: string
        description: Link to Readme.md file for the Release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022        
        
concurrency:
  group: rabbitmq-release
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

env:  
  ABS_NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }},
  ABS_NUGET_USERNAME: ${{ github.ACTOR }}

jobs:
  run-vector-tests:
    name: Run Vector Tests

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ github.TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Get installer        
        run: |
          Start-BitsTransfer -Source "https://github.com/abs-wavesight/cc-platform/releases/download/Installer/ComponentRegistryConfig.json" -Destination C:\abs\ComponentRegistryConfig.json
          Start-BitsTransfer -Source "https://github.com/abs-wavesight/cc-platform/releases/download/Installer/Abs.CommonCore.Installer.exe" -Destination C:\abs\Installer.exe
          
      - name: Download components       
        run: |
          C:\abs\Installer.exe download -r ComponentRegistryConfig.json -c RabbitMq -p $WINDOWS_VERSION:${{ inputs.windows-version }}

      - name: List contents
        run: |
          cmd /r dir /s c:\abs