name: RabbitMq Release

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: Name of the release
      tag:
        required: true
        type: string
        description: Unique tag for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022        
        
concurrency:
  group: rabbitmq-release
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

env:  
  ABS_NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }},
  ABS_NUGET_USERNAME: ${{ github.ACTOR }}
  REGISTRY: ghcr.io

jobs:
  release-component:
    name: Release Component
    uses: ./.github/workflows/shared-component-release.yml
      with:
        component_name: RabbitMq
        name: ${{ inputs.names }}
        tag: ${{ inputs.tag }}
        description: ${{ inputs.description }}
        windows-version: ${{ inputs.windows-version }}
