name: Vector Central Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      platform-commit-sha: # 6ac7551
        required: true
        type: string
        description: 7 character short SHA for the commit in cc-platform

concurrency:
  group: vector-central-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Vector Central Release
    uses: ./.github/workflows/release-shared-component.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      name: Vector Central Release ${{ matrix.windows-version }} ${{ inputs.version }}
      component_name: vector-central
      tag: vector-central-${{ matrix.windows-version }}-${{ inputs.version }}
      description: ${{ inputs.description }}
      component-params: -p `$WINDOWS_VERSION:${{ matrix.windows-version }} -p `$PLATFORM_COMMIT_SHA:${{ inputs.platform-commit-sha }}  
    secrets: inherit