name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: true
        type: string
        description: Tag to use for RabbitMQ release
      vector-site-version:
        required: true
        type: string
        description: Tag to use for Vector site release
      drex-version:
        required: true
        type: string
        description: Tag to use for Drex release
      openssl-version:
        required: true
        type: string
        description: Tag to use for OpenSSL release

concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Site System Release
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: site-system
      windows-version: ${{ matrix.windows-version }}
      system-config: SiteSystemConfig.json
      component-params: -p `$RABBIT_RELEASE_TAG:rabbitmq-${{ matrix.windows-version }}-${{ inputs.rabbitmq-version }} -p `$VECTOR_SITE_RELEASE_TAG:vector-site-${{ matrix.windows-version }}-${{ inputs.vector-site-version }} -p `$DREX_RELEASE_TAG:drex-${{ matrix.windows-version }}-${{ inputs.drex-version }} -p `$OPENSSL_RELEASE_TAG:openssl-${{ matrix.windows-version }}-${{ inputs.openssl-version }}
      release-name-prefix: Site System Release
    secrets: inherit