name: Observability Service Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: Unique version for the release
      description:
        required: false
        type: string
        description: Description of the release
      platform-commit-sha: # 6ac7551
        required: false
        type: string
        description: 7 character short SHA for the commit in cc-platform 

concurrency:
  group: observability-service-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-default-platform-commit-sha:
    name: Get Default Platform Commit SHA
    if: ${{ inputs.platform-commit-sha == '' }}
    uses: ./.github/workflows/shared-get-latest-container-version.yml
    with: 
      name: "cc-observability-service"
    secrets: inherit

  get-next-version:
    uses: abs-wavesight/cc-platform/.github/workflows/shared-define-version.yml@main
    with:
      major: 1
      minor: 0
      project_marker: "observability"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: false

  release-component:
    name: Observability Service Release
    needs: 
      - get-default-platform-commit-sha
      - get-next-version
    uses: ./.github/workflows/release-shared-component.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      name: ${{ inputs.version || needs.get-version.outputs.version }} Observability Service Release
      component_name: Observability-Service
      tag: ${{ inputs.version || needs.get-version.outputs.version }}_observability-service
      description: ${{ inputs.description || 'Observability Service' }}
      component-params: >         
        -p `$PLATFORM_COMMIT_SHA:${{ needs.get-default-platform-commit-sha.outputs.version || inputs.platform-commit-sha }} 
        -p `$OBSERVABILITY_VERSION:${{ needs.get-version.outputs.version || inputs.version }}
      windows-version: ${{ matrix.windows-version }}
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped
