name: Central System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: true
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-central-version:
        required: true
        type: string
        description: Version to use for Vector central release # v1.0.0

concurrency:
  group: central-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Central System Release
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: central-system
      windows-version: ${{ matrix.windows-version }}
      system-config: CentralSystemConfig.json
      component-params: -p `$RABBIT_RELEASE_TAG:rabbitmq-${{ matrix.windows-version }}-${{ inputs.rabbitmq-version }} -p `$VECTOR_CENTRAL_RELEASE_TAG:vector-central-${{ matrix.windows-version }}-${{ inputs.vector-central-version }}
      release-name-prefix: Central System Release
    secrets: inherit