name: Central System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-central-version:
        required: false
        type: string
        description: Version to use for Vector central release # v1.0.0

concurrency:
  group: central-system-release
  cancel-in-progress: true

jobs:
  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQ Release 2022"
    secrets: inherit

  get-default-vector-central-version:
    name: Get Default Vector Central Version
    if: ${{ inputs.vector-central-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Central Release 2022"
    secrets: inherit

  release-component:
    name: Central System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-central-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: central-system
      windows-version: ${{ matrix.windows-version }}
      system-config: CentralSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:rabbitmq-${{ matrix.windows-version }}-${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }} 
        -p `$VECTOR_CENTRAL_RELEASE_TAG:vector-central-${{ matrix.windows-version }}-${{ needs.get-default-vector-central-version.outputs.version || inputs.vector-central-version }}
      release-name-prefix: Central System Release
    secrets: inherit