name: Central System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      rabbitmq-tag:
        required: true
        type: string
        description: Tag to use for RabbitMQ release
      vector-central-tag:
        required: true
        type: string
        description: Tag to use for Vector central release

concurrency:
  group: central-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Central System Release
    uses: ./.github/workflows/release-shared-system.yml
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      windows-version: ${{ inputs.windows-version }}
      tag-prefix: central-system
      system-config: CentralSystemConfig.json
      component-params: -p `$RABBIT_RELEASE_TAG:${{ inputs.rabbitmq-tag }} -p `$VECTOR_CENTRAL_RELEASE_TAG:${{ inputs.vector-central-tag }}
      release-name-prefix: Central System Release
    secrets: inherit