name: Installer Release

on:
  workflow_dispatch:
        
concurrency:
  group: installer-release-${{ github.head_ref }}
  cancel-in-progress: true

env:
  NUGET_PACKAGE_PATH: ${{ github.workspace }}/.nuget/packages

jobs:
  release-installer:
    name: Installer Release
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        name: Checkout branch
          
      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ secrets.FETCH_ALL_RELEASES_TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
                   
      - name: Restore dependencies        
        run: dotnet restore tools/Installer/Installer/Installer.csproj --packages ${{ env.NUGET_PACKAGE_PATH }}

      - name: Publish
        run: dotnet publish tools/Installer/Installer/Installer.csproj --sc -c Release -f net8.0 -r win-x64 -p:PublishSingleFile=true -o ./
          
      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          body: Installer application
          name: Installer Release
          tag: Installer
          commit: main
          allowUpdates: true
          artifacts: "Abs.CommonCore.Installer.exe,./config/installer/*.json,./scripts/installer/Uninstall.cmd"