name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-site-version:
        required: false
        type: string
        description: Version to use for Vector site release # v1.0.0
      drex-message-version:
        required: false
        type: string
        description: Version to use for Drex Message release # v1.0.0
      drex-file-version:
        required: false
        type: string
        description: Version to use for Drex File release # v1.0.0
      openssl-version:
        required: false
        type: string
        description: Version to use for OpenSSL release # v1.0.0

concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQ Release 2022"
    secrets: inherit

  get-default-vector-site-version:
    name: Get Default Vector Site Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Site Release 2022"
    secrets: inherit

  get-default-drex-message-version:
    name: Get Default Drex Message Version
    if: ${{ inputs.drex-message-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex Message Release 2022"
    secrets: inherit

  get-default-drex-file-version:
    name: Get Default Drex File Version
    if: ${{ inputs.drex-file-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex File Release 2022"
    secrets: inherit

  get-default-openssl-version:
    name: Get Default OpenSSL Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "OpenSSL Release 2022"
    secrets: inherit

  release-component:
    name: Site System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-site-version
      - get-default-drex-message-version
      - get-default-drex-file-version
      - get-default-openssl-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: site-system
      windows-version: ${{ matrix.windows-version }}
      system-config: SiteSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:rabbitmq-${{ matrix.windows-version }}-${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }} 
        -p `$VECTOR_SITE_RELEASE_TAG:vector-site-${{ matrix.windows-version }}-${{ needs.get-default-vector-site-version || inputs.vector-site-version }} 
        -p `$DREX_MESSAGE_RELEASE_TAG:drex-message-${{ matrix.windows-version }}-${{ needs.get-default-drex-message-version || inputs.drex-message-version }} 
        -p `$DREX_FILE_RELEASE_TAG:drex-file-${{ matrix.windows-version }}-${{ needs.get-default-drex-file-version || inputs.drex-file-version }}
        -p `$OPENSSL_RELEASE_TAG:openssl-${{ matrix.windows-version }}-${{ needs.get-default-openssl-version || inputs.openssl-version }}
      release-name-prefix: Site System Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped