name: Central Core Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: Unique version for the release
      description:
        required: false
        type: string
        description: Description of the release
      notification-adapter-version:
        required: false
        type: string
        description: Version to use for Notification adapter release # v100

concurrency:
  group: central-observability-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next Version
    if: ${{ inputs.version == '' }}
    uses: abs-wavesight/cc-platform/.github/workflows/shared-define-version.yml@main
    with:
      major: 1
      minor: 0
      project_marker: "observability-central"
      develop_branch: "main"
      increment: true

  get-default-notification-adapter-version:
    name: Get Default Notification adapter Version
    if: ${{ inputs.notification-adapter-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex-notification-adapter"
      name: "Drex Notification Adapter Release"
    secrets: inherit

  release-component:
    name: Central Observability Release
    needs: 
      - get-default-notification-adapter-version
      - get-next-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2022" ]
    with:
      version: ${{ inputs.version || needs.get-next-version.outputs.version }}
      description: ${{ inputs.description || 'Central Observability Release' }}
      tag-prefix: central-observability
      windows-version: ${{ matrix.windows-version }}
      system-config: CentralObservabilityConfig.json
      component-params: >
        -p `$DREX_NOTIFICATION_ADAPTER_RELEASE_TAG:${{ needs.get-default-system-monitor-version.outputs.version || inputs.notification-adapter-version }}_drex_notification_adapter
      release-name-prefix: Central Observability Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped