name: Vector Site Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      platform-commit-sha: # 6ac7551
        required: false
        type: string
        description: 7 character short SHA for the commit in cc-platform

concurrency:
  group: vector-site-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-default-platform-commit-sha:
    name: Get Default Platform Commit SHA
    if: ${{ inputs.platform-commit-sha == '' }}
    uses: ./.github/workflows/shared-get-latest-container-version.yml
    with: 
      name: "vector"
    secrets: inherit

  release-component:
    name: Vector Site Release
    needs: get-default-platform-commit-sha
    uses: ./.github/workflows/release-shared-component.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      name: Vector Site Release ${{ matrix.windows-version }} ${{ inputs.version }}
      component_name: vector-site
      tag: vector-site-${{ matrix.windows-version }}-${{ inputs.version }}
      description: ${{ inputs.description }}
      component-params: >
        -p `$WINDOWS_VERSION:${{ matrix.windows-version }} 
        -p `$PLATFORM_COMMIT_SHA:${{ needs.get-default-platform-commit-sha.outputs.version || inputs.platform-commit-sha }}
      windows-version: ${{ matrix.windows-version }}
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped