name: RabbitMq Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      platform-commit-sha: # 6ac7551
        required: true
        type: string
        description: 7 character short SHA for the commit in cc-platform 

concurrency:
  group: rabbitmq-release
  cancel-in-progress: true

jobs:
  release-component:
    name: RabbitMQ Release
    uses: ./.github/workflows/release-shared-component.yml
    with:
      name: RabbitMQ Release ${{ inputs.windows-version }} ${{ inputs.version }}
      component_name: RabbitMq
      tag: rabbitmq-${{ inputs.windows-version }}-${{ inputs.version }}
      description: ${{ inputs.description }}
      component-params: -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$PLATFORM_COMMIT_SHA:${{ inputs.platform-commit-sha }}
    secrets: inherit
