name: Vector Site Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: Unique version for the release
      description:
        required: false
        type: string
        description: Description of the release
      platform-commit-sha: # 6ac7551
        required: false
        type: string
        description: 7 character short SHA for the commit in cc-platform

concurrency:
  group: vector-site-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-default-platform-commit-sha:
    name: Get Default Platform Commit SHA
    if: ${{ inputs.platform-commit-sha == '' }}
    uses: ./.github/workflows/shared-get-latest-container-version.yml
    with: 
      name: "vector"
    secrets: inherit

  get-current-version:
    name: Get Current Vector Central Version
    if: ${{ inputs.version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Site Release"
    secrets: inherit

  get-next-version:
    name: Get Next Vector Central Version
    needs: get-current-version
    if: ${{ inputs.version == '' }}
    uses: christian-draeger/increment-semantic-version@1.0.3
    with:
      current-version: ${{ needs.get-current-version.outputs.version }}
      version-fragment: 'feature'
    secrets: inherit

  release-component:
    name: Vector Site Release
    needs: 
      - get-default-platform-commit-sha
      - get-next-version
    uses: ./.github/workflows/release-shared-component.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      name: ${{ inputs.version || needs.get-next-version.outputs.next-version }} Vector Site Release
      component_name: vector-site
      tag: ${{ inputs.version || needs.get-next-version.outputs.next-version }}-vector-site
      description: ${{ inputs.description || '' }}
      component-params: >        
        -p `$PLATFORM_COMMIT_SHA:${{ needs.get-default-platform-commit-sha.outputs.version || inputs.platform-commit-sha }}
      windows-version: ${{ matrix.windows-version }}
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped