name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-site-version:
        required: false
        type: string
        description: Version to use for Vector site release # v1.0.0
      drex-message-version:
        required: false
        type: string
        description: Version to use for Drex Message release # v1.0.0
      drex-file-version:
        required: false
        type: string
        description: Version to use for Drex File release # v1.0.0
      openssl-version:
        required: false
        type: string
        description: Version to use for OpenSSL release # v1.0.0

concurrency:
  group: site-system-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQ Release"
    secrets: inherit

  get-default-vector-site-version:
    name: Get Default Vector Site Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Site Release"
    secrets: inherit

  get-default-drex-message-version:
    name: Get Default Drex Message Version
    if: ${{ inputs.drex-message-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex Message Release"
    secrets: inherit

  get-default-drex-file-version:
    name: Get Default Drex File Version
    if: ${{ inputs.drex-file-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex File Release"
    secrets: inherit

  get-default-openssl-version:
    name: Get Default OpenSSL Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "OpenSSL Release"
    secrets: inherit

  release-component:
    name: Site System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-site-version
      - get-default-drex-message-version
      - get-default-drex-file-version
      - get-default-openssl-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: site-system
      windows-version: ${{ matrix.windows-version }}
      system-config: SiteSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }}-rabbitmq 
        -p `$VECTOR_SITE_RELEASE_TAG:${{ needs.get-default-vector-site-version.outputs.version || inputs.vector-site-version }}-vector-site
        -p `$DREX_MESSAGE_RELEASE_TAG:${{ needs.get-default-drex-message-version.outputs.version || inputs.drex-message-version }}-drex-message 
        -p `$DREX_FILE_RELEASE_TAG:${{ needs.get-default-drex-file-version.outputs.version || inputs.drex-file-version }}-drex-file
        -p `$OPENSSL_RELEASE_TAG:${{ needs.get-default-openssl-version.outputs.version || inputs.openssl-version }}-openssl
      release-name-prefix: Site System Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped
