name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: true
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-site-version:
        required: true
        type: string
        description: Version to use for Vector site release # v1.0.0
      drex-version:
        required: true
        type: string
        description: Version to use for Drex release # v1.0.0
      openssl-version:
        required: true
        type: string
        description: Version to use for OpenSSL release # v1.0.0

concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  get:
    name: Get rabbit version
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.previousTag }}
      output2: ${{ steps.step1.outputs.previousSecondTag }}
      output3: ${{ steps.step1.outputs.previousThirdTag }}
    steps:
    - name: step1
      id: step1
      uses: ankur-lt/get-previous-stable-releases@1.0.2
      with:
        user: "${{ github.actor }}"
        repoName: "https://github.com/abs-wavesight/cc-platform"
        accessToken: "${{ secrets.FETCH_ALL_RELEASES_TOKEN }}"
    - name: debug
      id: step2
      run: |
        echo "previousTag: ${{ steps.step1.outputs.previousTag }}"
        echo "previousSecondTag: ${{ steps.step1.outputs.previousSecondTag }}"
        echo "previousThirdTag: ${{ steps.step1.outputs.previousThirdTag }}"

  release-component:
    needs: get
    name: Site System Release
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: site-system
      windows-version: ${{ matrix.windows-version }}
      system-config: SiteSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:rabbitmq-${{ matrix.windows-version }}-${{ inputs.rabbitmq-version }} 
        -p `$VECTOR_SITE_RELEASE_TAG:vector-site-${{ matrix.windows-version }}-${{ inputs.vector-site-version }} 
        -p `$DREX_RELEASE_TAG:drex-${{ matrix.windows-version }}-${{ inputs.drex-version }} 
        -p `$OPENSSL_RELEASE_TAG:openssl-${{ matrix.windows-version }}-${{ inputs.openssl-version }}
      release-name-prefix: Site System Release
    secrets: inherit