name: Site System Nano Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: Unique version for the release
      description:
        required: false
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v100
      vector-site-version:
        required: false
        type: string
        description: Version to use for Vector site release # v100
      drex-message-version:
        required: false
        type: string
        description: Version to use for Drex Message release # v100
      drex-file-version:
        required: false
        type: string
        description: Version to use for Drex File release # v100
      openssl-version:
        required: false
        type: string
        description: Version to use for OpenSSL release # v100
      disco-version:
        required: false
        type: string
        description: Version to use for disco release # v100
      observability-service-version:
        required: false
        type: string
        description: Version to use for Observability Service release # v100
      message-scheduler-version:
        required: false
        type: string
        description: Version to use for Message Scheduler release # v100

concurrency:
  group: site-system-nano-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next Version
    if: ${{ inputs.version == '' }}
    uses: abs-wavesight/cc-platform/.github/workflows/shared-define-version.yml@main
    with:
      major: 1
      minor: 0
      project_marker: "system-site"
      release_branch: "releases/1_0_1"
      develop_branch: "main"
      increment: true

  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Nano Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQNano Release"
    secrets: inherit

  get-default-vector-site-version:
    name: Get Default Vector Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Release"
    secrets: inherit

  get-default-drex-message-version:
    name: Get Default Drex Message Version
    if: ${{ inputs.drex-message-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex Message Release"
    secrets: inherit

  get-default-drex-file-version:
    name: Get Default Drex File Version
    if: ${{ inputs.drex-file-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex File Release"
    secrets: inherit

  get-default-openssl-version:
    name: Get Default OpenSSL Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "OpenSSL Release"
    secrets: inherit

  get-default-disco-version:
    name: Get Default Disco Version
    if: ${{ inputs.disco-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-disco"
      name: "Disco Release"
    secrets: inherit

  get-default-observability-service-version:
    name: Get Default Observability Service Version
    if: ${{ inputs.observability-service-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Observability Service Release"
    secrets: inherit

  get-default-message-scheduler-version:
    name: Get Default Message Scheduler Version
    if: ${{ inputs.message-scheduler-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-scheduler"
      name: "Message Scheduler Release"
    secrets: inherit

  release-component:
    name: Site System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-site-version
      - get-default-drex-message-version
      - get-default-drex-file-version
      - get-default-openssl-version
      - get-next-version
      - get-default-disco-version
      - get-default-observability-service-version
      - get-default-message-scheduler-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version || needs.get-next-version.outputs.version }}
      description: ${{ inputs.description || 'Site System Nano Release' }}
      tag-prefix: site-system-nano
      windows-version: ${{ matrix.windows-version }}
      system-config: SiteSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }}_rabbitmq
        -p `$VECTOR_RELEASE_TAG:${{ needs.get-default-vector-site-version.outputs.version || inputs.vector-site-version }}_vector
        -p `$DREX_MESSAGE_RELEASE_TAG:${{ needs.get-default-drex-message-version.outputs.version || inputs.drex-message-version }}_drex-message 
        -p `$DREX_FILE_RELEASE_TAG:${{ needs.get-default-drex-file-version.outputs.version || inputs.drex-file-version }}_drex-file
        -p `$OPENSSL_RELEASE_TAG:${{ needs.get-default-openssl-version.outputs.version || inputs.openssl-version }}_openssl
        -p `$DISCO_RELEASE_TAG:${{ needs.get-default-disco-version.outputs.version || inputs.disco-version }}_disco
        -p `$OBSERVABILITY_SERVICE_RELEASE_TAG:${{ needs.get-default-observability-service-version.outputs.version || inputs.observability-service-version }}_observability-service
        -p `$MESSAGE_SCHEDULER_RELEASE_TAG:${{ needs.get-default-message-scheduler-version.outputs.version || inputs.message-scheduler-version }}_message-scheduler
      release-name-prefix: Site System Nano Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped
