name: Kdi System Nano Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: Unique version for the release
      description:
        required: false
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v100
      vector-site-version:
        required: false
        type: string
        description: Version to use for Vector site release # v100
      drex-message-version:
        required: false
        type: string
        description: Version to use for Drex Message release # v100
      drex-file-version:
        required: false
        type: string
        description: Version to use for Drex File release # v100
      openssl-version:
        required: false
        type: string
        description: Version to use for OpenSSL release # v100
      disco-version:
        required: false
        type: string
        description: Version to use for disco release # v100
      kdi-version:
        required: false
        type: string
        description: Version to use for kdi release # v100

concurrency:
  group: kdi-system-nano-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-next-version:
    name: Get Next Version
    if: ${{ inputs.version == '' }}
    uses: ./.github/workflows/shared-get-next-release-version.yml
    with:
      repo: "cc-platform"
      name: "Kdi System Nano Release"
    secrets: inherit

  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQ Release"
    secrets: inherit

  get-default-vector-site-version:
    name: Get Default Vector Site Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Site Release"
    secrets: inherit

  get-default-drex-message-version:
    name: Get Default Drex Message Version
    if: ${{ inputs.drex-message-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex Message Release"
    secrets: inherit

  get-default-drex-file-version:
    name: Get Default Drex File Version
    if: ${{ inputs.drex-file-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-drex"
      name: "Drex File Release"
    secrets: inherit

  get-default-openssl-version:
    name: Get Default OpenSSL Version
    if: ${{ inputs.vector-site-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "OpenSSL Release"
    secrets: inherit

  get-default-disco-version:
    name: Get Default Disco Version
    if: ${{ inputs.disco-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-disco"
      name: "Disco Release"
    secrets: inherit

  get-default-kdi-version:
    name: Get Default Kdi Version
    if: ${{ inputs.kdi-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-adapters-kdi"
      name: "Kdi Release"
    secrets: inherit

  release-component:
    name: Kdi System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-site-version
      - get-default-drex-message-version
      - get-default-drex-file-version
      - get-default-openssl-version
      - get-next-version
      - get-default-disco-version
      - get-default-kdi-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2022" ]
    with:
      version: ${{ inputs.version || needs.get-next-version.outputs.version }}
      description: ${{ inputs.description || 'Kdi System Nano Release' }}
      tag-prefix: kdi-system-nano
      windows-version: ${{ matrix.windows-version }}
      system-config: KdiSystemNanoConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }}_rabbitmq
        -p `$VECTOR_SITE_RELEASE_TAG:${{ needs.get-default-vector-site-version.outputs.version || inputs.vector-site-version }}_vector-site
        -p `$DREX_MESSAGE_RELEASE_TAG:${{ needs.get-default-drex-message-version.outputs.version || inputs.drex-message-version }}_drex-message 
        -p `$DREX_FILE_RELEASE_TAG:${{ needs.get-default-drex-file-version.outputs.version || inputs.drex-file-version }}_drex-file
        -p `$OPENSSL_RELEASE_TAG:${{ needs.get-default-openssl-version.outputs.version || inputs.openssl-version }}_openssl
        -p `$DISCO_RELEASE_TAG:${{ needs.get-default-disco-version.outputs.version || inputs.disco-version }}_disco
        -p `$KDI_RELEASE_TAG:${{ needs.get-default-kdi-version.outputs.version || inputs.kdi-version }}_kdi
      release-name-prefix: Kdi System Nano Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped
