name: Central System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      rabbitmq-version:
        required: false
        type: string
        description: Version to use for RabbitMQ release # v1.0.0
      vector-central-version:
        required: false
        type: string
        description: Version to use for Vector central release # v1.0.0
      sftp-service-version:
        required: false
        type: string
        description: Version to use for Sftp Service release # v1.0.0

concurrency:
  group: central-system-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-default-rabbitmq-version:
    name: Get Default RabbitMQ Version
    if: ${{ inputs.rabbitmq-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "RabbitMQ Release"
    secrets: inherit

  get-default-vector-central-version:
    name: Get Default Vector Central Version
    if: ${{ inputs.vector-central-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Vector Central Release"
    secrets: inherit

  get-default-sftp-service-version:
    name: Get Default Sftp Service Version
    if: ${{ inputs.sftp-service-version == '' }}
    uses: ./.github/workflows/shared-get-latest-release-version.yml
    with:
      repo: "cc-platform"
      name: "Sftp Service Release"
    secrets: inherit

  release-component:
    name: Central System Release
    needs: 
      - get-default-rabbitmq-version
      - get-default-vector-central-version
      - get-default-sftp-service-version
    uses: ./.github/workflows/release-shared-system.yml
    strategy:
      matrix:
        windows-version: [ "2019", "2022" ]
    with:
      version: ${{ inputs.version }}
      description: ${{ inputs.description }}
      tag-prefix: central-system
      windows-version: ${{ matrix.windows-version }}
      system-config: CentralSystemConfig.json
      component-params: >
        -p `$RABBIT_RELEASE_TAG:${{ needs.get-default-rabbitmq-version.outputs.version || inputs.rabbitmq-version }}-rabbitmq
        -p `$VECTOR_CENTRAL_RELEASE_TAG:${{ needs.get-default-vector-central-version.outputs.version || inputs.vector-central-version }}-vector-central
        -p `$SFTP_SERVICE_RELEASE_TAG:${{ needs.get-default-sftp-service-version.outputs.version || inputs.sftp-service-version }}-sftp-service
      release-name-prefix: Central System Release
    secrets: inherit
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') }} # Needed to ensure the full workflow runs even if dependencies skipped