name: Branch Counter Workflow

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: "The branch for which to retrieve or increment the counter (defaults to current branch)"        
        default: ${{ github.ref_name }}
      project_marker:
        type: string
        description: "Use this marker if you have multiple projects within a single repository that each require individual counters."
        default: ""
      increment:
        type: boolean
        description: "Incrementing the counter (default: false)"        
        default: false      
    outputs:
      branchCounter:
        value: ${{ jobs.branch_counter.outputs.branchCounter }}

jobs:
  branch_counter:
    runs-on: ubuntu-latest
    outputs:
      branchCounter: ${{ steps.counter.outputs.branchCounter }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:        
          submodules: false

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine Counter
        id: counter
        shell: bash
        run: |          
          BRANCH_NAME="${{ inputs.branch }}"          
         
          TAGS=$(git tag -l "counter-${{ inputs.project_marker }}-${BRANCH_NAME}-*")

          if [ -z "$TAGS" ]; then            
            COUNTER=1
          else           
            LAST_TAG=$(echo "$TAGS" | sort -V | tail -n 1)
            COUNTER=$(echo "$LAST_TAG" | awk -F '-' '{print $NF}')
          fi
          
          if [ "${{ inputs.increment}}" = "true" ]; then
            COUNTER=$((COUNTER + 1))
            NEW_TAG="counter-${{ inputs.project_marker }}-${BRANCH_NAME}-${COUNTER}"
            echo "Incrementing counter. New tag: $NEW_TAG"
           
            git tag "$NEW_TAG"
            git push origin "$NEW_TAG"           
          fi

          echo "branchCounter=${COUNTER}" >> $GITHUB_OUTPUT


      - name: Display Counter
        run: echo "Branch-specific counter is ${{ steps.counter.outputs.branchCounter }}"


