name: Shared - Component Release

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: Name of the release    
      component_name:
        required: true
        type: string
        description: Name of the component to release      
      tag:
        required: true
        type: string
        description: Unique tag for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: string
        description: Windows version for the Release  

jobs:
  release-component:
    name: Component Release
    runs-on: windows-2019

    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+8
          format: 'YYYYMMDDHHmmss'
          
      - name: Build Tag
        id: build-tag
        uses: Entepotenz/change-string-case-action@v1
        with:
          string: ${{ inputs.tag }}-${{ steps.time.outputs.time }}
          
      - uses: actions/checkout@v3
        name: Checkout branch

      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ github.TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Download installer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: Abs.CommonCore.Installer.exe
          target: Installer.exe
          token: ${{ secrets.GITHUB_TOKEN }}                   
      
      - name: Download installer config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: ComponentRegistryConfig.json
          target: ComponentRegistryConfig.json
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download components       
        run: |
          .\Installer.exe download -r ComponentRegistryConfig.json -c ${{ inputs.component_name }} -p `$ABS_PATH:c:/abs -p `$WINDOWS_VERSION:${{ inputs.windows-version }}

      - name: Compress contents
        run: |
          .\Installer.exe compress -s c:/abs/installer -d Release.zip
          
      - name: Chunk contents
        run: |
          .\Installer.exe chunk -s Release.zip -d .\ --size (1 * 1024 * 1024 * 1024)
          
      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ inputs.description }}
          name: ${{ inputs.name }}
          tag: ${{ steps.build-tag.outputs.lowercase }}
          commit: main
          artifacts: "Release.zip*"