name: Shared - System Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      windows-version:
        required: true
        type: string
        description: Windows version for the Release
      tag-prefix: # drex
        required: true
        type: string
        description: Prefix for the release tag
      release-body: # Drex: ...tag... \r\n RabbitMQ: ...tag...
        required: true
        type: string
        description: Body text for the release
      release-name-prefix: # Drex Release
        required: true
        type: string
        description: Body text for the release        
      downloader-config: # SiteSystemDownloaderConfig.json
        required: true
        type: string
        description: Name of the downloader config file
      installer-config: # Drex Release
        required: true
        type: string
        description: Name of the installer config file        
      downloader-parameters: # -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$RABBIT_RELEASE_TAG:${{ inputs.rabbitmq-tag }} -p `$VECTOR_SITE_RELEASE_TAG:${{ inputs.vector-site-tag }} -p `$DREX_RELEASE_TAG:${{ inputs.drex-tag }}
        required: true
        type: string
        description: Full parameter list for downloader command      
      components-list: # "RabbitMQ", "Vector-Site", "Drex"
        required: true
        type: string
        description: List of components to process        
      release-fetch-token: # secrets.FETCH_ALL_RELEASES_TOKEN
        required: true
        type: string
        description: Token to use for fetching releases

jobs:
  release-component:
    name: Shared - System Release
    runs-on: windows-2019

    steps:   
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYYMMDDHHmmss'
          
      - name: Build Release Body
        id: release_body        
        uses: mkungla/actions-set-text-output@v1
        with:
          text: ${{ inputs.release-body }}
          
      - name: Build Tag
        id: build-tag
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ inputs.tag-prefix }}-${{ inputs.windows-version }}-${{ inputs.version }}-${{ steps.time.outputs.time }}
          
      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ inputs.release-fetch-token }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Download installer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: Abs.CommonCore.Installer.exe
          target: Installer.exe
          token: ${{ inputs.release-fetch-token }}                   
      
      - name: Download installer registry config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: SystemRegistryConfig.json
          target: SystemRegistryConfig.json
          token: ${{ inputs.release-fetch-token }}
          
      - name: Download installer download config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: ${{ inputs.downloader-config }}
          target: SystemDownloaderConfig.json
          token: ${{ inputs.release-fetch-token }}          
          
      - name: Download installer install config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: ${{ inputs.installer-config }}
          target: SystemInstallerConfig.json
          token: ${{ inputs.release-fetch-token }}              
          
      - name: Download components       
        run: |
          .\Installer.exe download -r SystemRegistryConfig.json -d SystemDownloaderConfig.json ${{ inputs.downloader-parameters }}

      - name: Process Components   
        run: |
          foreach($component in (${{ inputs.components-list }}))
          {
            .\Installer.exe unchunk -s c:/abs/temp/$component -d c:/abs/temp/$component/Release.zip
            .\Installer.exe uncompress -s c:/abs/temp/$component/Release.zip -d c:/abs/installer          
          }          

      - name: Compress contents
        run: |
          .\Installer.exe compress -s c:/abs/installer -d Release.zip
          
      - name: Chunk contents
        run: |
          .\Installer.exe chunk -s Release.zip -d .\ --size (1 * 1024 * 1024 * 1024)          

      - name: Remove extra files
        run: |
          if ([System.IO.File]::Exists('Release.zip.part1')) { rm Release.zip }
          
      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release-body.outputs.value }}
          name: ${{ inputs.release-name-prefix }} ${{ inputs.windows-version }} ${{ inputs.version }}
          tag: ${{ steps.build-tag.outputs.lowercase }}
          commit: main
          artifacts: "Release.zip*,Installer.exe,SystemRegistryConfig.json,SystemInstallerConfig.json"