name: Shared - System Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: string
        description: Windows version for the Release
      tag-prefix:
        required: true
        type: string
        description: Prefix to use for tag
      system-config:
        required: true
        type: string
        description: System config file to use   
      component-params: # -p ... -p ...
        required: true
        type: string
        description: Full parameter list for components
      release-name-prefix: # Central System Release
        required: true
        type: string
        description: Prefix to use for release name       

jobs:
  release-component:
    name: System Release
    runs-on: windows-2019

    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYYMMDDHHmmss'
          
      - name: Build Tag
        id: build-tag
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ inputs.tag-prefix }}-${{ inputs.windows-version }}-${{ inputs.version }}-${{ steps.time.outputs.time }}

      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ secrets.FETCH_ALL_RELEASES_TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Download installer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: Abs.CommonCore.Installer.exe
          target: Installer.exe
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}                   
      
      - name: Download installer registry config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: SystemRegistryConfig.json
          target: SystemRegistryConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}
          
      - name: Download installer system config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: ${{ inputs.system-config }}
          target: SystemConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}                          

      - name: Download installer uninstaller
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: Uninstall.cmd
          target: Uninstall.cmd
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}    
          
      - name: Download components       
        run: |
          .\Installer.exe download -r SystemRegistryConfig.json -dc SystemConfig.json -p `$WINDOWS_VERSION:${{ inputs.windows-version }} ${{ inputs.component-params }}

      - name: Process Components   
        run: |
          .\Installer.exe unchunk -s c:/abs/temp/`$component -d c:/abs/temp/`$component/Release.zip -c SystemConfig.json
          .\Installer.exe uncompress -s c:/abs/temp/`$component/Release.zip -d c:/abs/installer -c SystemConfig.json

      - name: Bundle installer
        run: |
          xcopy Installer.exe c:/abs/installer
          xcopy Uninstall.cmd c:/abs/installer

      - name: Compress contents
        run: |
          .\Installer.exe compress -s c:/abs/installer -d Release.zip
          
      - name: Chunk contents
        run: |
          .\Installer.exe chunk -s Release.zip -d .\ --size (1 * 1024 * 1024 * 1024) -rs
         
      - name: Build release body
        run: |
          .\Installer.exe release-body -o release_body.txt -p "`$DESCRIPTION:${{ inputs.description }}" -p `$WINDOWS_VERSION:${{ inputs.windows-version }} ${{ inputs.component-params }}

      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release_body.txt
          name: ${{ inputs.release-name-prefix }} ${{ inputs.windows-version }} ${{ inputs.version }}
          tag: ${{ steps.build-tag.outputs.lowercase }}
          commit: main
          artifacts: "Release.zip*,Installer.exe,SystemRegistryConfig.json,SystemConfig.json"