name: Shared - Component Release

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: Name of the release    
      component_name:
        required: true
        type: string
        description: Name of the component to release      
      tag:
        required: true
        type: string
        description: Unique tag for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: string
        description: Windows version for the Release  
      commit-sha: # 6ac7551
        required: true
        type: string
        description: 7 character short SHA for the commit

jobs:
  release-component:
    name: Component Release
    runs-on: windows-2019
    
    steps:    
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYYMMDDHHmmss'
          
      - name: Build Tag
        id: build-tag
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ inputs.tag }}-${{ steps.time.outputs.time }}
          
      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ secrets.FETCH_ALL_RELEASES_TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Download installer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'abs-wavesight/cc-platform'
          version: tags/Installer
          file: Abs.CommonCore.Installer.exe
          target: Installer.exe
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}   
      
      - name: Download installer config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'abs-wavesight/cc-platform'
          version: tags/Installer
          file: ComponentRegistryConfig.json
          target: ComponentRegistryConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}
          
      - name: Download components       
        run: |
          .\Installer.exe download -r ComponentRegistryConfig.json -c ${{ inputs.component_name }} -p `$ABS_PATH:c:/abs -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$COMMIT_SHA:${{ inputs.commit-sha }}
          .\Installer.exe install -r ComponentRegistryConfig.json -c ${{ inputs.component_name }} -p `$ABS_PATH:c:/abs -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$COMMIT_SHA:${{ inputs.commit-sha }}

      - name: Compress contents
        run: |
          .\Installer.exe compress -s c:/abs/installer -d Release.zip
          
      - name: Chunk contents
        run: |
          .\Installer.exe chunk -s Release.zip -d .\ --size (1 * 1024 * 1024 * 1024) -rs         
      
      - name: Build release body
        run: |
          .\Installer.exe release-body -o release_body.txt -p "`$DESCRIPTION:${{ inputs.description }}" -p `$ABS_PATH:c:/abs -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$COMMIT_SHA:${{ inputs.commit-sha }}
      
      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release_body.txt
          name: ${{ inputs.name }}
          tag: ${{ steps.build-tag.outputs.lowercase }}
          commit: main
          artifacts: "Release.zip*"