name: Branch Counter Workflow

on:
  workflow_call:
    outputs:
        branchCounter: 
            value: ${{ jobs.branch_counter.outputs.branchCounter }}

jobs:
  branch_counter:
    runs-on: ubuntu-latest
    outputs:
      branchCounter: ${{ steps.increment_counter.outputs.branchCounter }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:        
          submodules: false

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine and Increment Counter
        id: increment_counter
        shell: bash
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          TAGS=$(git tag -l "counter-${BRANCH_NAME}-*")

          if [ -z "$TAGS" ]; then          
            COUNTER=1
          else          
            LAST_TAG=$(echo "$TAGS" | sort -V | tail -n 1)
            COUNTER=$(echo "$LAST_TAG" | awk -F '-' '{print $NF}')
            COUNTER=$((COUNTER + 1))
          fi

          NEW_TAG="counter-${BRANCH_NAME}-${COUNTER}"     
          echo "Branch-specific tag is $NEW_TAG"   

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"        

          echo "branchCounter=${COUNTER}" >> $Env:GITHUB_OUTPUT

      - name: Display Counter
        run: echo "Branch-specific counter is ${{ steps.increment_counter.outputs.branchCounter }}"


