name: 'Shared - Get Next Release version'

on:
    workflow_call:
      inputs:
        repo: # cc-platform
          description: 'Git repository name'
          type: string
          required: true
        name: # RabbitMQ Release
          description: 'Release name'
          type: string
          required: true
        owner:
          description: 'Repository owner'
          type: string
          required: false
          default: 'abs-wavesight'
        
      outputs:
        version:
          description: 'version'
          value: ${{ jobs.get-next-version.outputs.version }}
jobs:
    get-current-version:
        name: Get Current Version
        uses: ./.github/workflows/shared-get-latest-release-version.yml
        with:
          repo: "${{ inputs.repo }}"
          owner: "${{ inputs.owner }}"
          name: "${{ inputs.name }}"
        secrets: inherit
    
    get-next-version:
        name: Get Next Vector Central Version
        runs-on: ubuntu-latest
        needs: get-current-version
        outputs: 
            version: ${{ steps.bump_version.outputs.next-version }}
        steps:
        - name: bump_version
          id: bump_version
          shell: bash
          run: |
            original=$(echo "${{ needs.get-current-version.outputs.version }}" | sed 's/[^0-9]*//g')
            next=v$((original + 1))
            echo "::set-output name=next-version::${next}"