name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      rabbitmq-tag:
        required: true
        type: string
        description: Tag to use for RabbitMQ release
      vector-site-tag:
        required: true
        type: string
        description: Tag to use for Vector site release
      drex-tag:
        required: true
        type: string
        description: Tag to use for Drex release        
        
concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: System Release
    runs-on: windows-2019

    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYYMMDDHHmmss'
          
      - name: Build Tag
        id: build-tag
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: site-system-${{ inputs.windows-version }}-${{ inputs.version }}-${{ steps.time.outputs.time }}
          
      - name: Build Release Body
        id: release_body        
        uses: mkungla/actions-set-text-output@v1
        with:
          text: |
            ${{ inputs.description }}
            
            RabbitMQ: ${{ inputs.rabbitmq-tag }}
            Vector Site: ${{ inputs.vector-site-tag }}  
            Drex: ${{ inputs.drex-tag }}  

      - name: Nuget - Set Nuget credentials
        working-directory: ./
        run: |
          $AbsNugetUsername = "USERNAME"
          echo "ABS_NUGET_USERNAME=$AbsNugetUsername" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          $AbsNugetPassword = "${{ secrets.FETCH_ALL_RELEASES_TOKEN }}"
          echo "ABS_NUGET_PASSWORD=$AbsNugetPassword" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
                   
      - name: Download installer
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: Abs.CommonCore.Installer.exe
          target: Installer.exe
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}                   
      
      - name: Download installer registry config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: SystemRegistryConfig.json
          target: SystemRegistryConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}
          
      - name: Download installer download config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: SiteSystemDownloaderConfig.json
          target: SystemDownloaderConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}          
          
      - name: Download installer install config
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/Installer
          file: SiteSystemInstallerConfig.json
          target: SystemInstallerConfig.json
          token: ${{ secrets.FETCH_ALL_RELEASES_TOKEN }}              
          
      - name: Download components       
        run: |
          .\Installer.exe download -r SystemRegistryConfig.json -d SystemDownloaderConfig.json -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$RABBIT_RELEASE_TAG:${{ inputs.rabbitmq-tag }} -p `$VECTOR_SITE_RELEASE_TAG:${{ inputs.vector-site-tag }} -p `$DREX_RELEASE_TAG:${{ inputs.drex-tag }}

      - name: Process Components   
        run: |
          foreach($component in ("RabbitMQ", "Vector-Site", "Drex"))
          {
            .\Installer.exe unchunk -s c:/abs/temp/$component -d c:/abs/temp/$component/Release.zip
            .\Installer.exe uncompress -s c:/abs/temp/$component/Release.zip -d c:/abs/installer          
          }          

      - name: Compress contents
        run: |
          .\Installer.exe compress -s c:/abs/installer -d Release.zip
          
      - name: Chunk contents
        run: |
          .\Installer.exe chunk -s Release.zip -d .\ --size (1 * 1024 * 1024 * 1024)          

      - name: Remove extra files
        run: |
          if ([System.IO.File]::Exists('Release.zip.part1')) { rm Release.zip }
          
      - name: Build release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release_body.outputs.value }}
          name: Site System Release ${{ inputs.windows-version }} ${{ inputs.version }}
          tag: ${{ steps.build-tag.outputs.lowercase }}
          commit: main
          artifacts: "Release.zip*,Installer.exe,SystemRegistryConfig.json,SystemInstallerConfig.json"