name: Site System Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      rabbitmq-tag:
        required: true
        type: string
        description: Tag to use for RabbitMQ release
      vector-site-tag:
        required: true
        type: string
        description: Tag to use for Vector site release
      drex-tag:
        required: true
        type: string
        description: Tag to use for Drex release        
        
concurrency:
  group: site-system-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Site System Release
    runs-on: windows-2019

    steps:
      - name: Build Release Body
        id: release_body        
        uses: mkungla/actions-set-text-output@v1
        with:
          text: |
            ${{ inputs.description }}
            
            RabbitMQ: ${{ inputs.rabbitmq-tag }}
            Vector Site: ${{ inputs.vector-site-tag }}  
            Drex: ${{ inputs.drex-tag }}
            
      - name: System Release             
        uses: ./.github/workflows/shared-system-release.yml
        with:
            version: ${{ inputs.version }}
            windows-version: ${{ inputs.windows-version }}
            tag-prefix: site-system
            release-body: ${{ steps.release_body.outputs.value }}
            release-name-prefix: Site System Release
            downloader-config: SiteSystemDownloaderConfig.json
            installer-config: SiteSystemInstallerConfig.json
            downloader-parameters: -p `$WINDOWS_VERSION:${{ inputs.windows-version }} -p `$RABBIT_RELEASE_TAG:${{ inputs.rabbitmq-tag }} -p `$VECTOR_SITE_RELEASE_TAG:${{ inputs.vector-site-tag }} -p `$DREX_RELEASE_TAG:${{ inputs.drex-tag }}
            components-list: "RabbitMQ", "Vector-Site", "Drex"
            release-name-prefix: Site System Release
        secrets: inherit