name: Vector Central Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Unique version for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022
      full-commit-sha: # 6ac75515362a8121594772b31437e8bea6fa16cd
        required: true
        type: string
        description: Full SHA for the commit
      short-commit-sha: # 6ac7551
        required: true
        type: string
        description: Short SHA for the commit        

concurrency:
  group: vector-central-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Vector Central Release
    uses: ./.github/workflows/shared-component-release.yml
    with:
      name: Vector Central Release ${{ inputs.windows-version }} ${{ inputs.version }}
      component_name: vector-central
      tag: vector-central-${{ inputs.windows-version }}-${{ inputs.version }}
      description: ${{ inputs.description }}
      windows-version: ${{ inputs.windows-version }}
      full-commit-sha: ${{ inputs.full-commit-sha }}
      short-commit-sha: ${{ inputs.short-commit-sha }}      
    secrets: inherit