name: Vector Release

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: Name of the release
      tag:
        required: true
        type: string
        description: Unique tag for the release
      description:
        required: true
        type: string
        description: Description of the release
      windows-version:
        required: true
        type: choice
        description: Windows version for the Release
        options:
        - 2019
        - 2022        
        
concurrency:
  group: vector-release
  cancel-in-progress: true

jobs:
  release-component:
    name: Vector Release
    uses: ./.github/workflows/shared-component-release.yml
    with:
      component_name: vector
      name: ${{ inputs.names }}
      tag: ${{ inputs.tag }}
      description: ${{ inputs.description }}
      windows-version: ${{ inputs.windows-version }}
